[package]
name = "hx"
version = "25.07.1"
description = "A post-modern modal text editor"
homepage = "https://github.com/helix-editor/helix"
license = ""
type = "cli"

[discovery]
github = "helix-editor/helix"
tag_pattern = "{{version}}"
semver_only = true
include_prereleases = false

[assets]
url_template = "https://github.com/helix-editor/helix/releases/download/{{version}}/helix-{{version}}-{{target}}-macos.tar.xz"
universal = false

[assets.targets]
arm64 = "aarch64"
x86_64 = "aarch64"

[checksums]
vendor_type = "sha256"
skip = true

[install]
strategy = "link"
bin = ["hx"]
lib = []
include = []
script = ""

[hints]
post_install = ""
