[package]
name = "xh"
description = "Friendly and fast tool for sending HTTP requests"
homepage = "https://github.com/ducaale/xh"
license = ""

[discovery]
github = "ducaale/xh"
tag_pattern = "v{{version}}"
include_prereleases = false

[assets]
universal = false
skip_checksums = false

[assets.x86_64-macos]
suffix = "x86_64-apple-darwin.tar.gz"

[assets.arm64-macos]
suffix = "aarch64-apple-darwin.tar.gz"

[install]
bin = ["xh"]
lib = []
include = []
script = ""

[hints]
post_install = ""
