[package]
name = "pulumi"
description = "Infrastructure as Code in any programming language"
homepage = "https://github.com/pulumi/pulumi"
license = ""

[discovery]
github = "pulumi/pulumi"
tag_pattern = "v{{version}}"
include_prereleases = false

[assets]
universal = false
skip_checksums = false

[assets.arm64-macos]
suffix = "darwin-arm64.tar.gz"

[assets.x86_64-macos]
suffix = "darwin-x64.tar.gz"

[install]
bin = ["pulumi"]
lib = []
include = []
script = ""

[hints]
post_install = ""
