[package]
name = "lima"
description = "Linux virtual machines (and containers) on macOS"
homepage = "https://github.com/lima-vm/lima"
license = "Apache-2.0"

[discovery]
github = "lima-vm/lima"
tag_pattern = "v{{version}}"
include_prereleases = false

[assets]
universal = false
skip_checksums = false

[assets.arm64-macos]
suffix = "Darwin-arm64.tar.gz"

[assets.x86_64-macos]
suffix = "Darwin-x86_64.tar.gz"

[install]
bin = ["limactl"]
lib = []
include = []
script = ""

[dependencies]

[hints]
post_install = ""
