[package]
name = "podman"
version = "5.7.1"
description = "A daemonless container engine for developing, managing, and running OCI Containers"
homepage = "https://github.com/containers/podman"
license = ""
type = "cli"

[discovery]
github = "containers/podman"
tag_pattern = "v{{version}}"
include_prereleases = false

[assets]
url_template = "https://github.com/containers/podman/releases/download/v{{version}}/podman-remote-release-darwin_{{target}}.zip"
universal = false

[assets.targets]
arm64 = "arm64"
x86_64 = "amd64"

[checksums]
vendor_type = "sha256"
skip = false

[install]
strategy = "link"
bin = ["podman"]
lib = []
include = []
script = ""

[hints]
post_install = ""
