[package]
name = "viddy"
version = "1.3.0"
description = "A modern watch command"
homepage = "https://github.com/sachaos/viddy"
license = ""
type = "cli"

[discovery]
github = "sachaos/viddy"
tag_pattern = "v{{version}}"
semver_only = true
include_prereleases = false

[assets]
url_template = "https://github.com/sachaos/viddy/releases/download/v{{version}}/viddy-v{{version}}-macos-{{target}}.tar.gz"
universal = false

[assets.targets]
x86_64 = "x86_64"
arm64 = "arm64"

[checksums]
vendor_type = "sha256"
skip = false

[install]
strategy = "link"
bin = ["viddy"]
lib = []
include = []
script = ""

[hints]
post_install = ""
