[package]
name = "dua"
description = "A tool to conveniently learn about the disk usage of directories, fast!"
homepage = "https://github.com/Byron/dua-cli"

[discovery]
github = "Byron/dua-cli"
tag_pattern = "v{{version}}"

[assets]
arm64-macos = { suffix = "aarch64-apple-darwin.tar.gz" }
x86_64-macos = { suffix = "x86_64-apple-darwin.tar.gz" }

[install]
bin = ["dua"]
