[package]
name = "duf"
version = "0.9.1"
description = "Disk Usage/Free Utility - a better 'df' alternative"
homepage = "https://github.com/muesli/duf"
license = ""
type = "cli"

[discovery]
github = "muesli/duf"
tag_pattern = "v{{version}}"
semver_only = true
include_prereleases = false

[assets]
url_template = "https://github.com/muesli/duf/releases/download/v{{version}}/duf_{{version}}_darwin_{{target}}.tar.gz"
universal = false

[assets.targets]
x86_64 = "x86_64"
arm64 = "arm64"

[checksums]
vendor_type = "sha256"
skip = false

[install]
strategy = "link"
bin = ["duf"]
lib = []
include = []
script = ""

[hints]
post_install = ""
