[package]
name = "duf"
description = "Disk Usage/Free Utility - a better 'df' alternative"
homepage = "https://github.com/muesli/duf"
license = ""

[discovery]
github = "muesli/duf"
tag_pattern = "v{{version}}"
include_prereleases = false

[assets]
universal = false
skip_checksums = false

[assets.arm64-macos]
suffix = "arm64.tar.gz"

[assets.x86_64-macos]
suffix = "x86_64.tar.gz"

[install]
bin = ["duf"]
lib = []
include = []
script = ""

[hints]
post_install = ""
