[package]
name = "dust"
description = "A more intuitive version of 'du' in Rust"
homepage = "https://github.com/bootandy/dust"
license = ""

[discovery]
github = "bootandy/dust"
tag_pattern = "v{{version}}"
include_prereleases = false

[assets]
universal = false
skip_checksums = false

[assets.arm64-macos]
suffix = "aarch64-apple-darwin.tar.gz"

[assets.x86_64-macos]
suffix = "x86_64-apple-darwin.tar.gz"

[install]
bin = ["dust"]
lib = []
include = []
script = ""

[hints]
post_install = ""
