[package]
name = "wezterm"
description = "A GPU-accelerated cross-platform terminal emulator."
homepage = "https://wezfurlong.org/wezterm"

[discovery]
github = "wez/wezterm"
tag_pattern = "{{version}}"

[assets]
arm64-macos = { regex = "WezTerm-macos-.*\\.zip" }
x86_64-macos = { regex = "WezTerm-macos-.*\\.zip" }

[install]
bin = ["wezterm"]
