[package]
name = "dbmate"
description = "A lightweight, framework-agnostic database migration tool."
homepage = "https://github.com/amacneil/dbmate"

[discovery]
github = "amacneil/dbmate"
tag_pattern = "v{{version}}"

[assets]
arm64-macos = { suffix = "macos-arm64" }
x86_64-macos = { suffix = "macos-amd64" }

[install]
bin = ["dbmate"]
