[package]
name = "logseq"
description = "A privacy-first, open-source platform for knowledge management"
homepage = "https://github.com/logseq/logseq"
license = ""

[discovery]
github = "logseq/logseq"
tag_pattern = "{{version}}"
include_prereleases = false

[assets]
universal = false
skip_checksums = false

[assets.arm64-macos]
regex = "Logseq-darwin-arm64.*\\.dmg"

[assets.x86_64-macos]
regex = "Logseq-darwin-x64.*\\.dmg"

[install]
bin = ["logseq"]
lib = []
include = []
script = ""

[hints]
post_install = ""
