[package]
name = "tofu"
version = "1.11.2"
description = "Open-source Infrastructure as Code tool managed by the Linux Foundation"
homepage = "https://github.com/opentofu/opentofu"
license = ""
type = "cli"

[discovery]
github = "opentofu/opentofu"
tag_pattern = "v{{version}}"
semver_only = true
include_prereleases = false

[assets]
url_template = "https://github.com/opentofu/opentofu/releases/download/v{{version}}/tofu_{{version}}_darwin_{{target}}.tar.gz"
universal = false

[assets.targets]
arm64 = "arm64"
x86_64 = "amd64"

[checksums]
vendor_type = "sha256"
skip = false

[install]
strategy = "link"
bin = ["tofu"]
lib = []
include = []
script = ""

[hints]
post_install = ""
