[package]
name = "tokei"
description = "Count your code, quickly."
homepage = "https://github.com/XAMPPRocky/tokei"

[discovery]
github = "XAMPPRocky/tokei"
tag_pattern = "v{{version}}"

[assets]
arm64-macos = { regex = "tokei-.*-aarch64-apple-darwin\\.tar\\.gz" }
x86_64-macos = { regex = "tokei-.*-x86_64-apple-darwin\\.tar\\.gz" }

[install]
bin = ["tokei"]
