[package]
name = "readline"
description = "GNU Readline library"
homepage = "https://tiswww.case.edu/php/chet/readline/rltop.html"
license = "GPL-3.0"
tags = ["library", "terminal"]

[discovery]
manual = ["8.2"] # Readline versions are weirdly released on FTP, manual for now

[assets]
arm64-macos = { build = true }
x86_64-macos = { build = true }

[source]
url = "https://ftp.gnu.org/gnu/readline/readline-{{version}}.tar.gz"
format = "tar.gz"

[build]
dependencies = []
script = """
./configure --prefix=$PREFIX
make -j$JOBS
make install
"""

[install]
bin = []
