[package]
name = "lazydocker"
version = "0.24.3"
description = "The lazier way to manage everything docker"
homepage = "https://github.com/jesseduffield/lazydocker"
license = ""
type = "cli"

[discovery]
github = "jesseduffield/lazydocker"
tag_pattern = "v{{version}}"
semver_only = true
include_prereleases = false

[assets]
url_template = "https://github.com/jesseduffield/lazydocker/releases/download/v{{version}}/lazydocker_{{version}}_Darwin_{{target}}.tar.gz"
universal = false

[assets.targets]
x86_64 = "x86_64"
arm64 = "arm64"

[checksums]
vendor_type = "sha256"
skip = false

[install]
strategy = "link"
bin = ["lazydocker"]
lib = []
include = []
script = ""

[hints]
post_install = ""
