[package]
name = "lazygit"
version = "0.57.0"
description = "Simple terminal UI for git commands"
homepage = "https://github.com/jesseduffield/lazygit"
license = ""
type = "cli"

[discovery]
github = "jesseduffield/lazygit"
tag_pattern = "v{{version}}"
semver_only = true
include_prereleases = false

[assets]
url_template = "https://github.com/jesseduffield/lazygit/releases/download/v{{version}}/lazygit_{{version}}_darwin_{{target}}.tar.gz"
universal = false

[assets.targets]
arm64 = "arm64"
x86_64 = "x86_64"

[checksums]
vendor_type = "sha256"
skip = false

[install]
strategy = "link"
bin = ["lazygit"]
lib = []
include = []
script = ""

[hints]
post_install = ""
