[package]
name = "lazydocker"
description = "The lazier way to manage everything docker"
homepage = "https://github.com/jesseduffield/lazydocker"
license = ""

[discovery]
github = "jesseduffield/lazydocker"
tag_pattern = "v{{version}}"
include_prereleases = false

[assets]
universal = false
skip_checksums = false

[assets.x86_64-macos]
suffix = "x86_64.tar.gz"

[assets.arm64-macos]
suffix = "arm64.tar.gz"

[install]
bin = ["lazydocker"]
lib = []
include = []
script = ""

[hints]
post_install = ""
