[package]
name = "lazygit"
description = "Simple terminal UI for git commands"
homepage = "https://github.com/jesseduffield/lazygit"
license = ""

[discovery]
github = "jesseduffield/lazygit"
tag_pattern = "v{{version}}"
include_prereleases = false

[assets]
universal = false
skip_checksums = false

[assets.arm64-macos]
suffix = "arm64.tar.gz"

[assets.x86_64-macos]
suffix = "x86_64.tar.gz"

[install]
bin = ["lazygit"]
lib = []
include = []
script = ""

[hints]
post_install = ""
