[package]
name = "qsv"
description = "CSV data-wrangling toolkit."
homepage = "https://github.com/dathere/qsv"

[discovery]
github = "dathere/qsv"
tag_pattern = "{{version}}"

[assets]
arm64-macos = { suffix = "aarch64-apple-darwin.zip" }
x86_64-macos = { suffix = "x86_64-apple-darwin.zip" }

[install]
bin = ["qsv"]
