[package]
name = "argocd"
description = "Declarative continuous deployment for Kubernetes"
homepage = "https://github.com/argoproj/argo-cd"
license = ""

[discovery]
github = "argoproj/argo-cd"
tag_pattern = "v{{version}}"
include_prereleases = false

[assets]
universal = false
skip_checksums = false

[assets.arm64-macos]
suffix = "darwin-arm64"

[assets.x86_64-macos]
suffix = "darwin-amd64"

[install]
bin = ["argocd"]
lib = []
include = []
script = ""

[hints]
post_install = ""
