[package]
name = "argocd"
version = "3.2.3"
description = "Declarative Continuous Deployment for Kubernetes"
homepage = "https://github.com/argoproj/argo-cd"
license = ""
type = "cli"

[discovery]
github = "argoproj/argo-cd"
tag_pattern = "v{{version}}"
semver_only = true
include_prereleases = false

[assets]
url_template = "https://github.com/argoproj/argo-cd/releases/download/v{{version}}/argocd-darwin-{{target}}"
universal = false

[assets.targets]
x86_64 = "amd64"
arm64 = "arm64"

[checksums]
url_template = "https://github.com/argoproj/argo-cd/releases/download/v{{version}}/cli_checksums.txt"
vendor_type = "sha256"
skip = false

[install]
strategy = "link"
bin = ["argocd"]
lib = []
include = []
script = ""

[hints]
post_install = ""
