[package]
name = "cmake"
description = "Cross-platform build system"
homepage = "https://github.com/Kitware/CMake"
license = ""

[discovery]
github = "Kitware/CMake"
tag_pattern = "v{{version}}"
include_prereleases = false

[assets]
universal = true
skip_checksums = false

[assets.arm64-macos]
regex = "cmake.*-macos-universal\\.tar\\.gz"

[assets.x86_64-macos]
regex = "cmake.*-macos-universal\\.tar\\.gz"

[install]
bin = ["cmake"]
lib = []
include = []
script = ""

[hints]
post_install = ""
