[package]
name = "osv-scanner"
description = "Vulnerability scanner written in Go"
homepage = "https://github.com/google/osv-scanner"
license = ""

[discovery]
github = "google/osv-scanner"
tag_pattern = "v{{version}}"
include_prereleases = false

[assets]
universal = false
skip_checksums = false

[assets.arm64-macos]
suffix = "darwin_arm64"

[assets.x86_64-macos]
suffix = "darwin_amd64"

[install]
bin = ["osv-scanner"]
lib = []
include = []
script = ""

[hints]
post_install = ""
