[package]
name = "osv-scanner"
version = "2.3.1"
description = "Vulnerability scanner for open-source dependencies"
homepage = "https://github.com/google/osv-scanner"
license = ""
type = "cli"

[discovery]
github = "google/osv-scanner"
tag_pattern = "v{{version}}"
include_prereleases = false

[assets]
url_template = "https://github.com/google/osv-scanner/releases/download/v{{version}}/osv-scanner_darwin_{{target}}"
universal = false

[assets.targets]
arm64 = "arm64"
x86_64 = "amd64"

[checksums]
vendor_type = "sha256"
skip = false

[install]
strategy = "link"
bin = ["osv-scanner"]
lib = []
include = []
script = ""

[hints]
post_install = ""
