[package]
name = "sd"
version = "1.0.0"
description = "Intuitive find & replace CLI (sed alternative)"
homepage = "https://github.com/chmln/sd"
license = ""
type = "cli"

[discovery]
github = "chmln/sd"
tag_pattern = "v{{version}}"
semver_only = true
include_prereleases = false

[assets]
url_template = "https://github.com/chmln/sd/releases/download/v{{version}}/sd-v{{version}}-{{target}}.tar.gz"
universal = false

[assets.targets]
x86_64 = "x86_64-apple-darwin"
arm64 = "aarch64-apple-darwin"

[checksums]
vendor_type = "sha256"
skip = true

[install]
strategy = "link"
bin = ["sd"]
lib = []
include = []
script = ""

[hints]
post_install = ""
