[package]
name = "sd"
description = "Intuitive find & replace CLI (sed alternative)"
homepage = "https://github.com/chmln/sd"
license = ""

[discovery]
github = "chmln/sd"
tag_pattern = "v{{version}}"
include_prereleases = false

[assets]
universal = false
skip_checksums = false

[assets.x86_64-macos]
suffix = "x86_64-apple-darwin.tar.gz"

[assets.arm64-macos]
suffix = "aarch64-apple-darwin.tar.gz"

[install]
bin = ["sd"]
lib = []
include = []
script = ""

[hints]
post_install = ""
