[package]
name = "lf"
description = "A terminal file manager implemented in Go"
homepage = "https://github.com/gokcehan/lf"
license = ""

[discovery]
github = "gokcehan/lf"
tag_pattern = "v{{version}}"
include_prereleases = false

[assets]
universal = false
skip_checksums = false

[assets.x86_64-macos]
suffix = "amd64.tar.gz"

[assets.arm64-macos]
suffix = "arm64.tar.gz"

[install]
bin = ["lf"]
lib = []
include = []
script = ""

[hints]
post_install = ""
