[package]
name = "btop"
description = "A monitor of resources that emphasizes the use and distribution of processor, memory, disks, network and processes."
homepage = "https://github.com/aristocratos/btop"

[discovery]
github = "aristocratos/btop"
tag_pattern = "v{{version}}"

[assets]
arm64-macos = { suffix = "aarch64-apple-darwin.tbz" }
x86_64-macos = { suffix = "x86_64-apple-darwin.tbz" }

[install]
bin = ["btop"]
