[package]
name = "syft"
description = "CLI tool and library for generating a Software Bill of Materials (SBOM) from container images and filesystems."
homepage = "https://github.com/anchore/syft"

[discovery]
github = "anchore/syft"
tag_pattern = "v{{version}}"

[assets]
arm64-macos = { suffix = "Darwin_arm64.tar.gz" }
x86_64-macos = { suffix = "Darwin_x86_64.tar.gz" }

[install]
bin = ["syft"]
