[package]
name = "syncthing"
version = "2.0.12"
description = "Open Source Continuous File Synchronization"
homepage = "https://github.com/syncthing/syncthing"
license = ""
type = "cli"

[discovery]
github = "syncthing/syncthing"
tag_pattern = "v{{version}}"
semver_only = true
include_prereleases = false

[assets]
url_template = "https://github.com/syncthing/syncthing/releases/download/v{{version}}/syncthing-macos-{{target}}-v{{version}}.zip"
universal = false

[assets.targets]
x86_64 = "amd64"
arm64 = "arm64"

[checksums]
vendor_type = "sha256"
skip = false

[install]
strategy = "link"
bin = ["syncthing"]
lib = []
include = []
script = ""

[hints]
post_install = ""
