[package]
name = "scc"
description = "Sloc, Cloc and Code: A tool similar to cloc, sloccount and tokei."
homepage = "https://github.com/boyter/scc"

[discovery]
github = "boyter/scc"
tag_pattern = "v{{version}}"

[assets]
arm64-macos = { suffix = "Darwin_arm64.tar.gz" }
x86_64-macos = { suffix = "Darwin_x86_64.tar.gz" }

[install]
bin = ["scc"]
