[package]
name = "sccache"
version = "0.12.0"
description = "Shared Compilation Cache"
homepage = "https://github.com/mozilla/sccache"
license = ""
type = "cli"

[discovery]
github = "mozilla/sccache"
tag_pattern = "v{{version}}"
semver_only = true
include_prereleases = false

[assets]
url_template = "https://github.com/mozilla/sccache/releases/download/v{{version}}/sccache-v{{version}}-{{target}}.tar.gz"
universal = false

[assets.targets]
arm64 = "aarch64-apple-darwin"
x86_64 = "x86_64-apple-darwin"

[checksums]
vendor_type = "sha256"
skip = false

[install]
strategy = "link"
bin = ["sccache"]
lib = []
include = []
script = ""

[hints]
post_install = ""
