[package]
name = "shuttle"
description = "Shuttle is a Rust-native cloud development platform."
homepage = "https://shuttle.rs"

[discovery]
github = "shuttle-hq/shuttle"
tag_pattern = "v{{version}}"

[assets]
arm64-macos = { suffix = "aarch64-apple-darwin.tar.gz" }
x86_64-macos = { suffix = "x86_64-apple-darwin.tar.gz" }

[install]
bin = ["shuttle"]
