[package]
name = "gping"
version = "1.20.1"
description = "Ping, but with a graph"
homepage = "https://github.com/orf/gping"
license = ""
type = "cli"

[discovery]
github = "orf/gping"
tag_pattern = "v{{version}}"
semver_only = true
include_prereleases = false

[assets]
url_template = "https://github.com/orf/gping/releases/download/gping-v{{version}}/gping-macOS-{{target}}.tar.gz"
universal = false

[assets.targets]
arm64 = "arm64"
x86_64 = "x86_64"

[checksums]
vendor_type = "sha256"
skip = true

[install]
strategy = "link"
bin = ["gping"]
lib = []
include = []
script = ""

[hints]
post_install = ""
