[package]
name = "golangci-lint"
description = "Fast linters runner for Go"
homepage = "https://github.com/golangci/golangci-lint"
license = ""

[discovery]
github = "golangci/golangci-lint"
tag_pattern = "v{{version}}"
include_prereleases = false

[assets]
universal = false
skip_checksums = false

[assets.arm64-macos]
suffix = "arm64.tar.gz"

[assets.x86_64-macos]
suffix = "amd64.tar.gz"

[install]
bin = ["golangci-lint"]
lib = []
include = []
script = ""

[hints]
post_install = ""
