[package]
name = "goreleaser"
version = "2.13.2"
description = "Release engineering, simplified"
homepage = "https://github.com/goreleaser/goreleaser"
license = ""
type = "cli"

[discovery]
github = "goreleaser/goreleaser"
tag_pattern = "v{{version}}"
include_prereleases = false

[assets]
url_template = "https://github.com/goreleaser/goreleaser/releases/download/v{{version}}/goreleaser_Darwin_{{target}}.tar.gz"
universal = false

[assets.targets]
x86_64 = "x86_64"
arm64 = "arm64"

[checksums]
url_template = "https://github.com/goreleaser/goreleaser/releases/download/v{{version}}/checksums.txt"
vendor_type = "sha256"
skip = false

[install]
strategy = "link"
bin = ["goreleaser"]
lib = []
include = []
script = ""

[hints]
post_install = ""
