[package]
name = "goreleaser"
description = "Release engineering, simplified"
homepage = "https://github.com/goreleaser/goreleaser"
license = ""

[discovery]
github = "goreleaser/goreleaser"
tag_pattern = "v{{version}}"
include_prereleases = false

[assets]
universal = false
skip_checksums = false

[assets.x86_64-macos]
suffix = "x86_64.tar.gz"

[assets.arm64-macos]
suffix = "arm64.tar.gz"

[install]
bin = ["goreleaser"]
lib = []
include = []
script = ""

[hints]
post_install = ""
