[package]
name = "sad"
version = "0.4.32"
description = "SAD! Space Age seD - A careful CLI search and replace with diff previews"
homepage = "https://github.com/ms-jpq/sad"
license = ""
type = "cli"

[discovery]
github = "ms-jpq/sad"
tag_pattern = "v{{version}}"
include_prereleases = false

[assets]
url_template = "https://github.com/ms-jpq/sad/releases/download/v{{version}}/{{target}}.zip"
universal = false

[assets.targets]
arm64 = "aarch64-apple-darwin"
x86_64 = "x86_64-apple-darwin"

[checksums]
vendor_type = "sha256"
skip = false

[install]
strategy = "link"
bin = ["sad"]
lib = []
include = []
script = ""

[hints]
post_install = ""
