[package]
name = "zoxide"
version = "0.9.8"
description = "A smarter cd command"
homepage = "https://github.com/ajeetdsouza/zoxide"
license = ""
type = "cli"

[discovery]
github = "ajeetdsouza/zoxide"
tag_pattern = "v{{version}}"
semver_only = true
include_prereleases = false

[assets]
url_template = "https://github.com/ajeetdsouza/zoxide/releases/download/v{{version}}/zoxide-{{version}}-{{target}}.tar.gz"
universal = false

[assets.targets]
arm64 = "aarch64-apple-darwin"
x86_64 = "x86_64-apple-darwin"

[checksums]
vendor_type = "sha256"
skip = false

[install]
strategy = "link"
bin = ["zoxide"]
lib = []
include = []
script = ""

[hints]
post_install = ""
