[package]
name = "zoxide"
description = "A smarter cd command. It remembers which directories you use most frequently, so you can \"jump\" to them in just a few keystrokes."
homepage = "https://github.com/ajeetdsouza/zoxide"

[discovery]
github = "ajeetdsouza/zoxide"
tag_pattern = "v{{version}}"

[assets]
arm64-macos = { suffix = "aarch64-apple-darwin.tar.gz" }
x86_64-macos = { suffix = "x86_64-apple-darwin.tar.gz" }

[install]
bin = ["zoxide"]
