[package]
name = "bat"
version = "0.26.1"
description = "A cat(1) clone with wings"
homepage = "https://github.com/sharkdp/bat"
license = "MIT OR Apache-2.0"

[source]
url = "https://github.com/sharkdp/bat/archive/v0.26.1.tar.gz"
blake3 = "5a3de674ad3fa40cd9784086f9b3c4fe1ce096e9a4aa60e186a309aba7a0ebbc"

[bottle.arm64]
url = "https://github.com/sharkdp/bat/releases/download/v0.26.1/bat-v0.26.1-aarch64-apple-darwin.tar.gz"
blake3 = "5a3de674ad3fa40cd9784086f9b3c4fe1ce096e9a4aa60e186a309aba7a0ebbc"

[install]
bin = ["bat"]
