[package]
name = "fzf"
version = "0.60.2"
description = "A command-line fuzzy finder"
type = "cli"

[source]
url = "https://github.com/junegunn/fzf/releases/download/v0.60.2/fzf-0.60.2-darwin_arm64.tar.gz"
blake3 = "7131f1f4eec87de29a2c4b9d8aa5e02e630a59a9a20d311226001aa4372d577a"

[bottle.arm64]
url = "https://github.com/junegunn/fzf/releases/download/v0.60.2/fzf-0.60.2-darwin_arm64.tar.gz"
blake3 = "7131f1f4eec87de29a2c4b9d8aa5e02e630a59a9a20d311226001aa4372d577a"

[install]
bin = ["fzf"]
