[package]
name = "hyperfine"
version = "1.19.0"
description = "A command-line benchmarking tool"
type = "cli"

[source]
url = "https://github.com/sharkdp/hyperfine/releases/download/v1.19.0/hyperfine-v1.19.0-aarch64-apple-darwin.tar.gz"
blake3 = "af92c9c3868e0ffcfd4375650958f00155f32acf1fe6205522b9d1f8a20c8c3c"

[bottle.arm64]
url = "https://github.com/sharkdp/hyperfine/releases/download/v1.19.0/hyperfine-v1.19.0-aarch64-apple-darwin.tar.gz"
blake3 = "af92c9c3868e0ffcfd4375650958f00155f32acf1fe6205522b9d1f8a20c8c3c"

[install]
bin = ["hyperfine"]
