[package]
name = "testbump"
version = "2.0.0"
description = "A short description of testbump"
homepage = "https://example.com"
license = "MIT"

[source]
url = "https://example.com/testbump-0.1.0.tar.gz"
blake3 = "0000000000000000000000000000000000000000000000000000000000000000"
strip_components = 0

[bottle.arm64]
url = "http://localhost:8000/dl_mock"
blake3 = "bf8953c218144189a45a444173247fb0e0a2e10b8c5e25dce9888764d95d1c29"
arch = "arm64"
macos = "14.0"

[dependencies]
runtime = []
build = []
optional = []

[install]
bin = ["testbump"]
lib = []
include = []
script = ""
