[package]
name = "glab"
description = "A GitLab CLI tool"
homepage = "https://github.com/profclems/glab"
license = ""

[discovery]
github = "profclems/glab"
tag_pattern = "v{{version}}"
include_prereleases = false

[assets]
universal = false
skip_checksums = false

[assets.x86_64-macos]
suffix = "x86_64.tar.gz"

[assets.arm64-macos]
suffix = "x86_64.tar.gz"

[install]
bin = ["glab"]
lib = []
include = []
script = ""

[hints]
post_install = ""
