[package]
name = "gleam"
description = "A friendly language for building type-safe, scalable systems!"
homepage = "https://gleam.run"

[discovery]
github = "gleam-lang/gleam"
tag_pattern = "v{{version}}"

[assets]
arm64-macos = { suffix = "aarch64-apple-darwin.tar.gz" }
x86_64-macos = { suffix = "x86_64-apple-darwin.tar.gz" }

[install]
bin = ["gleam"]
