[package]
name = "glow"
description = "Render markdown on the CLI, with pizzazz!"
homepage = "https://github.com/charmbracelet/glow"
license = ""

[discovery]
github = "charmbracelet/glow"
tag_pattern = "v{{version}}"
include_prereleases = false

[assets]
universal = false
skip_checksums = false

[assets.x86_64-macos]
suffix = "darwin_amd64.tar.gz"

[assets.arm64-macos]
suffix = "darwin_arm64.tar.gz"

[install]
bin = ["glow"]
lib = []
include = []
script = ""

[hints]
post_install = ""
