[package]
name = "amber"
version = "0.6.0"
description = "A code search / replace tool"
homepage = "https://github.com/dalance/amber"
license = ""
type = "cli"

[discovery]
github = "amber-lang/amber"
tag_pattern = "v{{version}}"
include_prereleases = false

[assets]
url_template = "https://github.com/amber-lang/amber/releases/download/v{{version}}/amber-{{target}}.tar.xz"
universal = false

[assets.targets]
x86_64 = "macos-x86_64"
arm64 = "macos-aarch64"

[checksums]
vendor_type = "sha256"
skip = false

[install]
strategy = "link"
bin = ["amber"]
lib = []
include = []
script = ""

[hints]
post_install = ""
