[package]
name = "alacritty"
description = "A cross-platform, OpenGL terminal emulator"
homepage = "https://github.com/alacritty/alacritty"
license = ""

[discovery]
github = "alacritty/alacritty"
tag_pattern = "v{{version}}"
include_prereleases = false

[assets]
universal = true
skip_checksums = false

[assets.arm64-macos]
suffix = ".dmg"

[assets.x86_64-macos]
suffix = ".dmg"

[install]
bin = ["alacritty"]
lib = []
include = []
script = ""

[hints]
post_install = ""
