[package]
name = "colima"
version = "0.9.1"
description = "Container runtimes on macOS (and Linux) with minimal setup"
homepage = "https://github.com/abiosoft/colima"
license = ""
type = "cli"

[discovery]
github = "abiosoft/colima"
tag_pattern = "v{{version}}"
semver_only = true
include_prereleases = false

[assets]
url_template = "https://github.com/abiosoft/colima/releases/download/v{{version}}/colima-Darwin-{{target}}"
universal = false

[assets.targets]
x86_64 = "x86_64"
arm64 = "arm64"

[checksums]
vendor_type = "sha256"
skip = true

[install]
strategy = "link"
bin = ["colima"]
lib = []
include = []
script = ""

[hints]
post_install = ""
