[package]
name = "colima"
description = "Container runtimes on macOS with minimal setup"
homepage = "https://github.com/abiosoft/colima"
license = ""

[discovery]
github = "abiosoft/colima"
tag_pattern = "v{{version}}"
include_prereleases = false

[assets]
universal = false
skip_checksums = false

[assets.arm64-macos]
suffix = "Darwin-arm64"

[assets.x86_64-macos]
suffix = "Darwin-x86_64"

[install]
bin = ["colima"]
lib = []
include = []
script = ""

[hints]
post_install = ""
