[package]
name = "cosign"
description = "Container Signing, Verification and Storage in an OCI registry"
homepage = "https://github.com/sigstore/cosign"
license = ""

[discovery]
github = "sigstore/cosign"
tag_pattern = "v{{version}}"
include_prereleases = false

[assets]
universal = false
skip_checksums = false

[assets.arm64-macos]
suffix = "darwin-arm64"

[assets.x86_64-macos]
suffix = "darwin-amd64"

[install]
bin = ["cosign"]
lib = []
include = []
script = ""

[hints]
post_install = ""
