[package]
name = "skaffold"
description = "Easy and Repeatable Kubernetes Development"
homepage = "https://github.com/GoogleContainerTools/skaffold"
license = ""

[discovery]
github = "GoogleContainerTools/skaffold"
tag_pattern = "v{{version}}"
include_prereleases = false

[assets]
universal = false
skip_checksums = false

[assets.arm64-macos]
suffix = "darwin-arm64"

[assets.x86_64-macos]
suffix = "darwin-amd64"

[install]
bin = ["skaffold"]
lib = []
include = []
script = ""

[hints]
post_install = ""
