[package]
name = "skaffold"
version = "2.17.0"
description = "Easy and Repeatable Kubernetes Development"
homepage = "https://github.com/GoogleContainerTools/skaffold"
license = ""
type = "cli"

[discovery]
github = "GoogleContainerTools/skaffold"
tag_pattern = "v{{version}}"
semver_only = true
include_prereleases = false

[assets]
url_template = "https://github.com/GoogleContainerTools/skaffold/releases/download/v{{version}}/skaffold-darwin-{{target}}"
universal = false

[assets.targets]
x86_64 = "amd64"
arm64 = "arm64"

[checksums]
vendor_type = "sha256"
skip = false

[install]
strategy = "link"
bin = ["skaffold"]
lib = []
include = []
script = ""

[hints]
post_install = ""
