[package]
name = "soft-serve"
description = "The mighty, self-hostable Git server for the command line"
homepage = "https://github.com/charmbracelet/soft-serve"
license = ""

[discovery]
github = "charmbracelet/soft-serve"
tag_pattern = "v{{version}}"
include_prereleases = false

[assets]
universal = false
skip_checksums = false

[assets.x86_64-macos]
suffix = "x86_64.tar.gz"

[assets.arm64-macos]
suffix = "arm64.tar.gz"

[install]
bin = ["soft-serve"]
lib = []
include = []
script = ""

[hints]
post_install = ""
