[package]
name = "opa"
description = "Open Policy Agent"
homepage = "https://github.com/open-policy-agent/opa"
license = ""

[discovery]
github = "open-policy-agent/opa"
tag_pattern = "v{{version}}"
include_prereleases = false

[assets]
universal = false
skip_checksums = false

[assets.arm64-macos]
suffix = "darwin_arm64"

[assets.x86_64-macos]
suffix = "darwin_amd64"

[install]
bin = ["opa"]
lib = []
include = []
script = ""

[hints]
post_install = ""
