[package]
name = "micro"
description = "A modern and intuitive terminal-based text editor"
homepage = "https://github.com/zyedidia/micro"
license = ""

[discovery]
github = "zyedidia/micro"
tag_pattern = "v{{version}}"
include_prereleases = false

[assets]
universal = false
skip_checksums = false

[assets.arm64-macos]
suffix = "arm64.tar.gz"

[assets.x86_64-macos]
suffix = "arm64.tar.gz"

[install]
bin = ["micro"]
lib = []
include = []
script = ""

[hints]
post_install = ""
