[package]
name = "onefetch"
description = "A command-line Git information tool written in Rust."
homepage = "https://onefetch.rs"

[discovery]
github = "o2sh/onefetch"
tag_pattern = "v{{version}}"

[assets]
universal = true
universal-macos = { suffix = "mac.tar.gz" }

[install]
bin = ["onefetch"]
