[package]
name = "typos"
description = "Source code spell checker"
homepage = "https://github.com/crate-ci/typos"
license = ""

[discovery]
github = "crate-ci/typos"
tag_pattern = "v{{version}}"
include_prereleases = false

[assets]
universal = false
skip_checksums = false

[assets.arm64-macos]
suffix = "aarch64-apple-darwin.tar.gz"

[assets.x86_64-macos]
suffix = "x86_64-apple-darwin.tar.gz"

[install]
bin = ["typos"]
lib = []
include = []
script = ""

[hints]
post_install = ""
