[package]
name = "k9s"
version = "0.50.16"
description = "Kubernetes CLI To Manage Your Clusters In Style!"
homepage = "https://github.com/derailed/k9s"
license = ""
type = "cli"

[discovery]
github = "derailed/k9s"
tag_pattern = "v{{version}}"
semver_only = true
include_prereleases = false

[assets]
url_template = "https://github.com/derailed/k9s/releases/download/v{{version}}/k9s_Darwin_{{target}}.tar.gz"
universal = false

[assets.targets]
arm64 = "arm64"
x86_64 = "amd64"

[checksums]
vendor_type = "sha256"
skip = false

[install]
strategy = "link"
bin = ["k9s"]
lib = []
include = []
script = ""

[hints]
post_install = ""
