[package]
name = "k9s"
description = "Kubernetes CLI To Manage Your Clusters In Style!"
homepage = "https://github.com/derailed/k9s"
license = ""

[discovery]
github = "derailed/k9s"
tag_pattern = "v{{version}}"
include_prereleases = false

[assets]
universal = false
skip_checksums = false

[assets.x86_64-macos]
suffix = "amd64.tar.gz"

[assets.arm64-macos]
suffix = "arm64.tar.gz"

[install]
bin = ["k9s"]
lib = []
include = []
script = ""

[hints]
post_install = ""
