[package]
name = "procs"
version = "0.14.10"
description = "A modern replacement for 'ps' written in Rust"
homepage = "https://github.com/dalance/procs"
license = ""
type = "cli"

[discovery]
github = "dalance/procs"
tag_pattern = "v{{version}}"
semver_only = true
include_prereleases = false

[assets]
url_template = "https://github.com/dalance/procs/releases/download/v{{version}}/procs-v{{version}}-{{target}}-mac.zip"
universal = false

[assets.targets]
x86_64 = "aarch64"
arm64 = "aarch64"

[checksums]
vendor_type = "sha256"
skip = false

[install]
strategy = "link"
bin = ["procs"]
lib = []
include = []
script = ""

[hints]
post_install = ""
