[package]
name = "yq"
description = "Portable command-line YAML, JSON, XML, CSV, TOML, HCL and properties processor"
homepage = "https://github.com/mikefarah/yq"
license = ""

[discovery]
github = "mikefarah/yq"
tag_pattern = "v{{version}}"
include_prereleases = false

[assets]
universal = false
skip_checksums = false

[assets.arm64-macos]
suffix = "darwin_arm64.tar.gz"

[assets.x86_64-macos]
suffix = "darwin_amd64.tar.gz"

[install]
bin = ["yq"]
lib = []
include = []
script = ""

[hints]
post_install = ""
