[package]
name = "yq"
version = "4.50.1"
description = "Portable command-line YAML, JSON, XML, CSV, TOML, HCL and properties processor"
homepage = "https://github.com/mikefarah/yq"
license = ""
type = "cli"

[discovery]
github = "mikefarah/yq"
tag_pattern = "v{{version}}"
semver_only = true
include_prereleases = false

[assets]
url_template = "https://github.com/mikefarah/yq/releases/download/v{{version}}/yq_darwin_{{target}}"
universal = false

[assets.targets]
x86_64 = "amd64"
arm64 = "arm64"

[checksums]
vendor_type = "sha256"
skip = false

[install]
strategy = "link"
bin = ["yq"]
lib = []
include = []
script = ""

[hints]
post_install = ""
