[package]
name = "atuin"
description = "Magical shell history"
homepage = "https://github.com/ellie/atuin"
license = ""

[discovery]
github = "atuinsh/atuin"
tag_pattern = "v{{version}}"
include_prereleases = false

[assets]
universal = false
skip_checksums = false

[assets.x86_64-macos]
suffix = "x86_64-apple-darwin.tar.gz"

[assets.arm64-macos]
suffix = "aarch64-apple-darwin.tar.gz"

[install]
bin = ["atuin"]
lib = []
include = []
script = ""

[hints]
post_install = ""
