[package]
name = "marp"
description = "CLI interface for Marp and Marpit-based converters"
homepage = "https://github.com/marp-team/marp-cli"
license = ""

[discovery]
github = "marp-team/marp-cli"
tag_pattern = "v{{version}}"
include_prereleases = false

[assets]
universal = true
skip_checksums = false

[assets.arm64-macos]
suffix = "-mac.tar.gz"

[assets.x86_64-macos]
suffix = "-mac.tar.gz"

[install]
bin = ["marp"]
lib = []
include = []
script = ""

[hints]
post_install = ""
