[package]
name = "starship"
description = "The minimal, blazing-fast, and infinitely customizable prompt for any shell!"
homepage = "https://github.com/starship/starship"
license = ""

[discovery]
github = "starship/starship"
tag_pattern = "v{{version}}"
include_prereleases = false

[assets]
universal = false
skip_checksums = false

[assets.arm64-macos]
suffix = "aarch64-apple-darwin.tar.gz"

[assets.x86_64-macos]
suffix = "x86_64-apple-darwin.tar.gz"

[install]
bin = ["starship"]
lib = []
include = []
script = ""

[hints]
post_install = ""
