[package]
name = "fzf"
description = "A command-line fuzzy finder"
homepage = "https://github.com/junegunn/fzf"
license = ""

[discovery]
github = "junegunn/fzf"
tag_pattern = "v{{version}}"
include_prereleases = false

[assets]
universal = false
skip_checksums = false

[assets.amd64-macos]
suffix = "darwin_amd64.tar.gz"

[assets.arm64-macos]
suffix = "darwin_arm64.tar.gz"

[install]
bin = ["fzf"]
lib = []
include = []
script = ""

[hints]
post_install = ""
