[package]
name = "asdf"
description = "Extendable version manager with support for Ruby, Node.js, Elixir, Erlang & more"
homepage = "https://github.com/asdf-vm/asdf"
license = ""

[discovery]
github = "asdf-vm/asdf"
tag_pattern = "v{{version}}"
include_prereleases = false

[assets]
universal = false
skip_checksums = false

[assets.arm64-macos]
suffix = "darwin-arm64.tar.gz"

[assets.x86_64-macos]
suffix = "darwin-amd64.tar.gz"

[install]
bin = ["asdf"]
lib = []
include = []
script = ""

[hints]
post_install = ""
