[package]
name = "asdf"
version = "0.18.0"
description = "Extendable version manager with support for Ruby, Node.js, Elixir, Erlang & more"
homepage = "https://github.com/asdf-vm/asdf"
license = ""
type = "cli"

[discovery]
github = "asdf-vm/asdf"
tag_pattern = "v{{version}}"
semver_only = true
include_prereleases = false

[assets]
url_template = "https://github.com/asdf-vm/asdf/releases/download/v{{version}}/asdf-v{{version}}-darwin-{{target}}.tar.gz"
universal = false

[assets.targets]
arm64 = "arm64"
x86_64 = "amd64"

[checksums]
vendor_type = "sha256"
skip = false

[install]
strategy = "link"
bin = ["asdf"]
lib = []
include = []
script = ""

[hints]
post_install = ""
