[package]
name = "ninja"
description = "Small build system with a focus on speed"
homepage = ""
license = ""

[discovery]
github = "ninja-build/ninja"
tag_pattern = "v{{version}}"
include_prereleases = false

[assets]
universal = true
skip_checksums = false

[assets.arm64-macos]
suffix = "-mac.zip"

[assets.x86_64-macos]
suffix = "-mac.zip"

[install]
bin = ["ninja"]
lib = []
include = []
script = ""

[hints]
post_install = ""
