[package]
name = "hugo"
description = "The world's fastest framework for building websites"
homepage = "https://github.com/gohugoio/hugo"
license = ""

[discovery]
github = "gohugoio/hugo"
tag_pattern = "v{{version}}"
include_prereleases = false

[assets]
universal = true
skip_checksums = false

[assets.arm64-macos]
regex = "hugo_.*_darwin-universal\\.tar\\.gz"

[assets.x86_64-macos]
regex = "hugo_.*_darwin-universal\\.tar\\.gz"

[install]
bin = ["hugo"]
lib = []
include = []
script = ""

[hints]
post_install = ""
