[package]
name = "delta"
description = "A viewer for git and diff output."
homepage = "https://github.com/dandavison/delta"

[discovery]
github = "dandavison/delta"
tag_pattern = "{{version}}"

[assets]
arm64-macos = { suffix = "aarch64-apple-darwin.tar.gz" }
x86_64-macos = { suffix = "x86_64-apple-darwin.tar.gz" }

[install]
bin = ["delta"]
