[package]
name = "deno"
description = "A modern runtime for JavaScript and TypeScript"
homepage = "https://github.com/denoland/deno"
license = ""

[discovery]
github = "denoland/deno"
tag_pattern = "v{{version}}"
include_prereleases = false

[assets]
universal = false
skip_checksums = false

[assets.arm64-macos]
suffix = "aarch64-apple-darwin.zip"

[assets.x86_64-macos]
suffix = "x86_64-apple-darwin.zip"

[install]
bin = ["deno"]
lib = []
include = []
script = ""

[hints]
post_install = ""
