[package]
name = "rclone"
description = "Rsync for cloud storage."
homepage = "https://rclone.org"

[discovery]
github = "rclone/rclone"
tag_pattern = "v{{version}}"

[assets]
arm64-macos = { regex = "rclone-v.*-osx-arm64\\.zip" }
x86_64-macos = { regex = "rclone-v.*-osx-amd64\\.zip" }

[install]
bin = ["rclone"]
