[package]
name = "slides"
version = "0.9.0"
description = "Terminal based presentation tool"
homepage = "https://github.com/maaslalani/slides"
license = ""
type = "cli"

[discovery]
github = "maaslalani/slides"
tag_pattern = "v{{version}}"
include_prereleases = false

[assets]
url_template = "https://github.com/maaslalani/slides/releases/download/v{{version}}/slides_{{version}}_darwin_{{target}}.tar.gz"
universal = false

[assets.targets]
arm64 = "arm64"
x86_64 = "amd64"

[checksums]
vendor_type = "sha256"
skip = false

[install]
strategy = "link"
bin = ["slides"]
lib = []
include = []
script = ""

[hints]
post_install = ""
