[package]
name = "slides"
description = "Terminal based presentation tool"
homepage = "https://github.com/maaslalani/slides"
license = ""

[discovery]
github = "maaslalani/slides"
tag_pattern = "v{{version}}"
include_prereleases = false

[assets]
universal = false
skip_checksums = false

[assets.arm64-macos]
suffix = "arm64.tar.gz"

[assets.x86_64-macos]
suffix = "amd64.tar.gz"

[install]
bin = ["slides"]
lib = []
include = []
script = ""

[hints]
post_install = ""
