[package]
name = "slsa-verifier"
description = "Verify provenance from SLSA compliant builders"
homepage = "https://github.com/slsa-framework/slsa-verifier"
license = ""

[discovery]
github = "slsa-framework/slsa-verifier"
tag_pattern = "v{{version}}"
include_prereleases = false

[assets]
universal = false
skip_checksums = false

[assets.x86_64-macos]
suffix = "darwin-amd64"

[assets.arm64-macos]
suffix = "darwin-arm64"

[install]
bin = ["slsa-verifier"]
lib = []
include = []
script = ""

[hints]
post_install = ""
