[package]
name = "bottom"
description = "A cross-platform graphical process/system monitor"
homepage = "https://github.com/ClementTsang/bottom"
license = ""

[discovery]
github = "ClementTsang/bottom"
tag_pattern = "v{{version}}"
include_prereleases = false

[assets]
universal = false
skip_checksums = false

[assets.arm64-macos]
suffix = "aarch64-apple-darwin.tar.gz"

[assets.x86_64-macos]
suffix = "x86_64-apple-darwin.tar.gz"

[install]
bin = ["btm"]
lib = []
include = []
script = ""

[hints]
post_install = ""
