[package]
name = "gdu"
description = "Fast disk usage analyzer with console interface written in Go."
homepage = "https://github.com/dundee/gdu"

[discovery]
github = "dundee/gdu"
tag_pattern = "v{{version}}"

[assets]
arm64-macos = { suffix = "darwin_arm64.tgz" }
x86_64-macos = { suffix = "darwin_amd64.tgz" }

[install]
bin = ["gdu"]
