[package]
name = "cloudflared"
description = "Cloudflare Tunnel client (formerly Argo Tunnel)."
homepage = "https://github.com/cloudflare/cloudflared"

[discovery]
github = "cloudflare/cloudflared"
tag_pattern = "{{version}}"

[assets]
arm64-macos = { suffix = "darwin-arm64.tgz" }
x86_64-macos = { suffix = "darwin-amd64.tgz" }

[install]
bin = ["cloudflared"]
