[package]
name = "fx"
description = "Terminal JSON viewer & processor"
homepage = "https://github.com/antonmedv/fx"
license = ""

[discovery]
github = "antonmedv/fx"
tag_pattern = "v{{version}}"
include_prereleases = false

[assets]
universal = false
skip_checksums = false

[assets.x86_64-macos]
suffix = "darwin_amd64"

[assets.arm64-macos]
suffix = "darwin_arm64"

[install]
bin = ["fx"]
lib = []
include = []
script = ""

[hints]
post_install = ""
