[package]
name = "curlie"
description = "The power of curl, the ease of use of httpie"
homepage = "https://github.com/rs/curlie"
license = ""

[discovery]
github = "rs/curlie"
tag_pattern = "v{{version}}"
include_prereleases = false

[assets]
universal = false
skip_checksums = false

[assets.arm64-macos]
suffix = "arm64.tar.gz"

[assets.x86_64-macos]
suffix = "amd64.tar.gz"

[install]
bin = ["curlie"]
lib = []
include = []
script = ""

[hints]
post_install = ""
