[package]
name = "transmission"
description = "Fast, easy, and free BitTorrent client"
homepage = "https://github.com/transmission/transmission"
license = ""

[discovery]
github = "transmission/transmission"
tag_pattern = "{{version}}"
include_prereleases = false

[assets]
universal = true
skip_checksums = false

[assets.arm64-macos]
regex = "Transmission.*\\.dmg"

[assets.x86_64-macos]
regex = "Transmission.*\\.dmg"

[install]
bin = ["transmission"]
lib = []
include = []
script = ""

[hints]
post_install = ""
