[package]
name = "trivy"
description = "Find vulnerabilities, misconfigurations, secrets, SBOM in containers, Kubernetes, code repositories, clouds and more"
homepage = "https://github.com/aquasecurity/trivy"
license = ""

[discovery]
github = "aquasecurity/trivy"
tag_pattern = "v{{version}}"
include_prereleases = false

[assets]
universal = false
skip_checksums = false

[assets.x86_64-macos]
suffix = "macOS-64bit.tar.gz"

[assets.arm64-macos]
suffix = "macOS-ARM64.tar.gz"

[install]
bin = ["trivy"]
lib = []
include = []
script = ""

[hints]
post_install = ""
