[package]
name = "trufflehog"
description = "Find, verify, and analyze leaked credentials"
homepage = "https://github.com/trufflesecurity/trufflehog"
license = ""

[discovery]
github = "trufflesecurity/trufflehog"
tag_pattern = "v{{version}}"
include_prereleases = false

[assets]
universal = false
skip_checksums = false

[assets.arm64-macos]
suffix = "arm64.tar.gz"

[assets.x86_64-macos]
suffix = "amd64.tar.gz"

[install]
bin = ["trufflehog"]
lib = []
include = []
script = ""

[hints]
post_install = ""
