[package]
name = "trufflehog"
version = "3.92.4"
description = "Find, verify, and analyze leaked credentials"
homepage = "https://github.com/trufflesecurity/trufflehog"
license = ""
type = "cli"

[discovery]
github = "trufflesecurity/trufflehog"
tag_pattern = "v{{version}}"
semver_only = true
include_prereleases = false

[assets]
url_template = "https://github.com/trufflesecurity/trufflehog/releases/download/v{{version}}/trufflehog_{{version}}_darwin_{{target}}.tar.gz"
universal = false

[assets.targets]
arm64 = "arm64"
x86_64 = "amd64"

[checksums]
vendor_type = "sha256"
skip = false

[install]
strategy = "link"
bin = ["trufflehog"]
lib = []
include = []
script = ""

[hints]
post_install = ""
