[package]
name = "etcd"
version = "3.6.7"
description = "Distributed reliable key-value store"
homepage = "https://github.com/etcd-io/etcd"
license = ""
type = "cli"

[discovery]
github = "etcd-io/etcd"
tag_pattern = "v{{version}}"
semver_only = true
include_prereleases = false

[assets]
url_template = "https://github.com/etcd-io/etcd/releases/download/v{{version}}/etcd-v{{version}}-darwin-{{target}}.zip"
universal = false

[assets.targets]
x86_64 = "amd64"
arm64 = "arm64"

[checksums]
vendor_type = "sha256"
skip = false

[install]
strategy = "link"
bin = ["etcd"]
lib = []
include = []
script = ""

[hints]
post_install = ""
