[package]
name = "etcd"
description = "Distributed reliable key-value store"
homepage = "https://github.com/etcd-io/etcd"
license = ""

[discovery]
github = "etcd-io/etcd"
tag_pattern = "v{{version}}"
include_prereleases = false

[assets]
universal = false
skip_checksums = false

[assets.arm64-macos]
suffix = "darwin-arm64.zip"

[assets.x86_64-macos]
suffix = "darwin-amd64.zip"

[install]
bin = ["etcd"]
lib = []
include = []
script = ""

[hints]
post_install = ""
