[package]
name = "bandwhich"
version = "0.23.1"
description = "Terminal bandwidth utilization tool"
homepage = "https://github.com/imsnif/bandwhich"
license = ""
type = "cli"

[discovery]
github = "imsnif/bandwhich"
tag_pattern = "v{{version}}"
include_prereleases = false

[assets]
url_template = "https://github.com/imsnif/bandwhich/releases/download/v{{version}}/bandwhich-v{{version}}-{{target}}.tar.gz"
universal = false

[assets.targets]
x86_64 = "x86_64-apple-darwin"
arm64 = "aarch64-apple-darwin"

[checksums]
vendor_type = "sha256"
skip = false

[install]
strategy = "link"
bin = ["bandwhich"]
lib = []
include = []
script = ""

[hints]
post_install = ""
