[package]
name = "bat"
description = "A cat clone with wings"
homepage = "https://github.com/sharkdp/bat"
license = ""

[discovery]
github = "sharkdp/bat"
tag_pattern = "v{{version}}"
include_prereleases = false

[assets]
universal = false
skip_checksums = false

[assets.x86_64-macos]
suffix = "x86_64-apple-darwin.tar.gz"

[assets.arm64-macos]
suffix = "aarch64-apple-darwin.tar.gz"

[install]
bin = ["bat"]
lib = []
include = []
script = ""

[hints]
post_install = ""
