[package]
name = "exa"
description = "A modern replacement for ls"
homepage = "https://github.com/ogham/exa"
license = ""

[discovery]
github = "ogham/exa"
tag_pattern = "v{{version}}"
include_prereleases = false

[assets]
universal = false
skip_checksums = false

[assets.arm64-macos]
regex = "exa-macos.*\\.zip"

[assets.x86_64-macos]
regex = "exa-macos.*\\.zip"

[install]
bin = ["exa"]
lib = []
include = []
script = ""

[hints]
post_install = ""
