[package]
name = "nushell"
description = "A modern shell for the GitHub era."
homepage = "https://www.nushell.sh"

[discovery]
github = "nushell/nushell"
tag_pattern = "{{version}}"

[assets]
arm64-macos = { suffix = "aarch64-apple-darwin.tar.gz" }
x86_64-macos = { suffix = "x86_64-apple-darwin.tar.gz" }

[install]
bin = ["nu"]
