[package]
name = "grex"
description = "A command-line tool for generating regular expressions"
homepage = "https://github.com/pemistahl/grex"
license = ""

[discovery]
github = "pemistahl/grex"
tag_pattern = "v{{version}}"
include_prereleases = false

[assets]
universal = false
skip_checksums = false

[assets.x86_64-macos]
suffix = "x86_64-apple-darwin.tar.gz"

[assets.arm64-macos]
suffix = "aarch64-apple-darwin.tar.gz"

[install]
bin = ["grex"]
lib = []
include = []
script = ""

[hints]
post_install = ""
