[package]
name = "zed"
description = "A high-performance, multiplayer code editor"
homepage = "https://github.com/zed-industries/zed"
license = ""

[discovery]
github = "zed-industries/zed"
tag_pattern = "v{{version}}"
include_prereleases = false

[assets]
universal = false
skip_checksums = false

[assets.x86_64-macos]
suffix = "x86_64.tar.gz"

[assets.arm64-macos]
suffix = "aarch64.tar.gz"

[install]
bin = ["zed"]
lib = []
include = []
script = ""

[hints]
post_install = ""
