[package]
name = "zed"
version = "0.217.3"
description = "A high-performance, multiplayer code editor"
homepage = "https://github.com/zed-industries/zed"
license = ""
type = "cli"

[discovery]
github = "zed-industries/zed"
tag_pattern = "v{{version}}"
include_prereleases = false

[assets]
url_template = "https://github.com/zed-industries/zed/releases/download/v{{version}}/Zed-{{target}}.dmg"
universal = false

[assets.targets]
x86_64 = "x86_64"
arm64 = "aarch64"

[checksums]
vendor_type = "sha256"
skip = false

[install]
strategy = "link"
bin = ["zed"]
lib = []
include = []
script = ""

[hints]
post_install = ""
