[package]
name = "hadolint"
version = "2.14.0"
description = "Haskell Dockerfile Linter"
homepage = "https://github.com/hadolint/hadolint"
license = ""
type = "cli"

[discovery]
github = "hadolint/hadolint"
tag_pattern = "v{{version}}"
include_prereleases = false

[assets]
url_template = "https://github.com/hadolint/hadolint/releases/download/v{{version}}/hadolint-macos-{{target}}"
universal = false

[assets.targets]
x86_64 = "x86_64"
arm64 = "arm64"

[checksums]
vendor_type = "sha256"
skip = false

[install]
strategy = "link"
bin = ["hadolint"]
lib = []
include = []
script = ""

[hints]
post_install = ""
