[package]
name = "tealdeer"
description = "A very fast implementation of tldr in Rust"
homepage = "https://github.com/dbrgn/tealdeer"
license = ""

[discovery]
github = "dbrgn/tealdeer"
tag_pattern = "v{{version}}"
include_prereleases = false

[assets]
universal = false
skip_checksums = false

[assets.arm64-macos]
suffix = "macos-aarch64"

[assets.x86_64-macos]
suffix = "macos-x86_64"

[install]
bin = ["tealdeer"]
lib = []
include = []
script = ""

[hints]
post_install = ""
