[package]
name = "termshot"
version = "0.6.0"
description = "Capture polished terminal output as images"
homepage = "https://github.com/homeport/termshot"
license = ""
type = "cli"

[discovery]
github = "homeport/termshot"
tag_pattern = "v{{version}}"
include_prereleases = false

[assets]
url_template = "https://github.com/homeport/termshot/releases/download/v{{version}}/termshot_{{version}}_darwin_{{target}}.tar.gz"
universal = false

[assets.targets]
x86_64 = "amd64"
arm64 = "arm64"

[checksums]
vendor_type = "sha256"
skip = false

[install]
strategy = "link"
bin = ["termshot"]
lib = []
include = []
script = ""

[hints]
post_install = ""
