[package]
name = "terragrunt"
description = "A flexible orchestration tool for scaling Infrastructure as Code"
homepage = "https://github.com/gruntwork-io/terragrunt"
license = ""

[discovery]
github = "gruntwork-io/terragrunt"
tag_pattern = "v{{version}}"
include_prereleases = false

[assets]
universal = false
skip_checksums = false

[assets.x86_64-macos]
suffix = "darwin_amd64.tar.gz"

[assets.arm64-macos]
suffix = "darwin_arm64.tar.gz"

[install]
bin = ["terragrunt"]
lib = []
include = []
script = ""

[hints]
post_install = ""
