[package]
name = "watchexec"
description = "Executes commands in response to file modifications"
homepage = "https://github.com/watchexec/watchexec"
license = ""

[discovery]
github = "watchexec/watchexec"
tag_pattern = "v{{version}}"
include_prereleases = false

[assets]
universal = false
skip_checksums = false

[assets.arm64-macos]
regex = "watchexec.*-aarch64-apple-darwin\\.tar\\.xz"

[assets.x86_64-macos]
regex = "watchexec.*-x86_64-apple-darwin\\.tar\\.xz"

[install]
bin = ["watchexec"]
lib = []
include = []
script = ""

[hints]
post_install = ""
