[package]
name = "ripgrep"
description = "A line-oriented search tool that recursively searches the current directory for a regex pattern"
homepage = "https://github.com/BurntSushi/ripgrep"
license = ""

[discovery]
github = "BurntSushi/ripgrep"
tag_pattern = "v{{version}}"
include_prereleases = false

[assets]
universal = false
skip_checksums = false

[assets.arm64-macos]
suffix = "aarch64-apple-darwin.tar.gz"

[assets.x86_64-macos]
suffix = "x86_64-apple-darwin.tar.gz"

[install]
bin = ["rg"]
lib = []
include = []
script = ""

[hints]
post_install = ""
