[package]
name = "fastfetch"
version = "2.56.1"
description = "A maintained, feature-rich and performance oriented, neofetch like system information tool"
homepage = "https://github.com/fastfetch-cli/fastfetch"
license = ""
type = "cli"

[discovery]
github = "fastfetch-cli/fastfetch"
tag_pattern = "{{version}}"
semver_only = true
include_prereleases = false

[assets]
url_template = "https://github.com/fastfetch-cli/fastfetch/releases/download/{{version}}/fastfetch-macos-{{target}}.tar.gz"
universal = false

[assets.targets]
x86_64 = "amd64"
arm64 = "aarch64"

[checksums]
vendor_type = "sha256"
skip = true

[install]
strategy = "link"
bin = ["fastfetch"]
lib = []
include = []
script = ""

[hints]
post_install = ""
