[package]
name = "fastfetch"
description = "A maintained, feature-rich and performance oriented, neofetch like system information tool"
homepage = "https://github.com/fastfetch-cli/fastfetch"
license = ""

[discovery]
github = "fastfetch-cli/fastfetch"
tag_pattern = "v{{version}}"
include_prereleases = false

[assets]
universal = false
skip_checksums = false

[assets.arm64-macos]
suffix = "macos-aarch64.tar.gz"

[assets.x86_64-macos]
suffix = "macos-amd64.tar.gz"

[install]
bin = ["fastfetch"]
lib = []
include = []
script = ""

[hints]
post_install = ""
