[package]
name = "just"
version = "1.45.0"
description = "Just a command runner"
homepage = "https://github.com/casey/just"
license = ""
type = "cli"

[discovery]
github = "casey/just"
tag_pattern = "{{version}}"
semver_only = true
include_prereleases = false

[assets]
url_template = "https://github.com/casey/just/releases/download/{{version}}/just-{{version}}-{{target}}.tar.gz"
universal = false

[assets.targets]
x86_64 = "x86_64-apple-darwin"
arm64 = "aarch64-apple-darwin"

[checksums]
url_template = "https://github.com/casey/just/releases/download/v{{version}}/SHA256SUMS"
vendor_type = "sha256"
skip = false

[install]
strategy = "link"
bin = ["just"]
lib = []
include = []
script = ""

[hints]
post_install = ""
