[package]
name = "just"
description = "Just a command runner"
homepage = "https://github.com/casey/just"
license = ""

[discovery]
github = "casey/just"
tag_pattern = "v{{version}}"
include_prereleases = false

[assets]
universal = false
skip_checksums = false

[assets.arm64-macos]
suffix = "aarch64-apple-darwin.tar.gz"

[assets.x86_64-macos]
suffix = "x86_64-apple-darwin.tar.gz"

[install]
bin = ["just"]
lib = []
include = []
script = ""

[hints]
post_install = ""
