[package]
name = "volta"
version = "2.0.2"
description = "The Hassle-Free JavaScript Tool Manager"
homepage = "https://github.com/volta-cli/volta"
license = ""
type = "cli"

[discovery]
github = "volta-cli/volta"
tag_pattern = "v{{version}}"
include_prereleases = false

[assets]
url_template = "https://github.com/volta-cli/volta/releases/download/v{{version}}/volta-{{version}}-macos.tar.gz"
universal = true

[checksums]
vendor_type = "sha256"
skip = true

[install]
strategy = "link"
bin = ["volta"]
lib = []
include = []
script = ""

[hints]
post_install = ""
