[package]
name = "volta"
description = "The Hassle-Free JavaScript Tool Manager"
homepage = "https://github.com/volta-cli/volta"
license = ""

[discovery]
github = "volta-cli/volta"
tag_pattern = "v{{version}}"
include_prereleases = false

[assets]
universal = true
skip_checksums = false

[assets.arm64-macos]
suffix = "macos.tar.gz"

[assets.x86_64-macos]
suffix = "macos.tar.gz"

[install]
bin = ["volta"]
lib = []
include = []
script = ""

[hints]
post_install = ""
