[package]
name = "air"
description = "Live reload for Go apps"
homepage = "https://github.com/air-verse/air"
license = ""

[discovery]
github = "air-verse/air"
tag_pattern = "v{{version}}"
include_prereleases = false

[assets]
universal = false
skip_checksums = false

[assets.x86_64-macos]
suffix = "darwin_amd64.tar.gz"

[assets.arm64-macos]
suffix = "darwin_arm64.tar.gz"

[install]
bin = ["air"]
lib = []
include = []
script = ""

[hints]
post_install = ""
