[package]
name = "vhs"
description = "Your CLI home video recorder"
homepage = "https://github.com/charmbracelet/vhs"
license = ""

[discovery]
github = "charmbracelet/vhs"
tag_pattern = "v{{version}}"
include_prereleases = false

[assets]
universal = false
skip_checksums = false

[assets.arm64-macos]
suffix = "arm64.tar.gz"

[assets.x86_64-macos]
suffix = "x86_64.tar.gz"

[install]
bin = ["vhs"]
lib = []
include = []
script = ""

[hints]
post_install = ""
