[package]
name = "vhs"
version = "0.10.0"
description = "Your CLI home video recorder"
homepage = "https://github.com/charmbracelet/vhs"
license = ""
type = "cli"

[discovery]
github = "charmbracelet/vhs"
tag_pattern = "v{{version}}"
semver_only = true
include_prereleases = false

[assets]
url_template = "https://github.com/charmbracelet/vhs/releases/download/v{{version}}/vhs_{{version}}_Darwin_{{target}}.tar.gz"
universal = false

[assets.targets]
arm64 = "arm64"
x86_64 = "x86_64"

[checksums]
url_template = "https://github.com/charmbracelet/vhs/releases/download/v{{version}}/checksums.txt"
vendor_type = "sha256"
skip = false

[install]
strategy = "link"
bin = ["vhs"]
lib = []
include = []
script = ""

[hints]
post_install = ""
