[package]
name = "git-lfs"
description = "Git extension for versioning large files"
homepage = "https://github.com/git-lfs/git-lfs"
license = ""

[discovery]
github = "git-lfs/git-lfs"
tag_pattern = "v{{version}}"
include_prereleases = false

[assets]
universal = false
skip_checksums = false

[assets.arm64-macos]
regex = "git-lfs-darwin-arm64.*\\.zip"

[assets.x86_64-macos]
regex = "git-lfs-darwin-amd64.*\\.zip"

[install]
bin = ["git-lfs"]
lib = []
include = []
script = ""

[hints]
post_install = ""
