[package]
name = "git-town"
description = "Generic, high-level git workflow support."
homepage = "https://www.git-town.com"

[discovery]
github = "git-town/git-town"
tag_pattern = "v{{version}}"

[assets]
arm64-macos = { suffix = "macos_arm_64.tar.gz" }
x86_64-macos = { suffix = "macos_intel_64.tar.gz" }

[install]
bin = ["git-town"]
