[package]
name = "github-cli"
description = "GitHub on the command line"
homepage = "https://github.com/cli/cli"
license = ""

[discovery]
github = "cli/cli"
tag_pattern = "v{{version}}"
include_prereleases = false

[assets]
universal = false
skip_checksums = false

[assets.arm64-macos]
suffix = "macOS_arm64.zip"

[assets.x86_64-macos]
suffix = "macOS_amd64.zip"

[install]
bin = ["gh"]
lib = []
include = []
script = ""

[hints]
post_install = ""
