[package]
name = "gitleaks"
description = "Scan git repos (or files) for secrets using regex and entropy."
homepage = "https://github.com/gitleaks/gitleaks"

[discovery]
github = "gitleaks/gitleaks"
tag_pattern = "v{{version}}"

[assets]
arm64-macos = { suffix = "darwin_arm64.tar.gz" }
x86_64-macos = { suffix = "darwin_x64.tar.gz" }

[install]
bin = ["gitleaks"]
