[package]
name = "gitui"
description = "Blazing fast terminal-ui for git written in rust"
homepage = "https://github.com/extrawurst/gitui"
license = ""

[discovery]
github = "gitui-org/gitui"
tag_pattern = "v{{version}}"
include_prereleases = false

[assets]
universal = true
skip_checksums = false

[assets.arm64-macos]
suffix = "mac.tar.gz"

[assets.x86_64-macos]
suffix = "mac.tar.gz"

[install]
bin = ["gitui"]
lib = []
include = []
script = ""

[hints]
post_install = ""
