[package]
name = "fd"
description = "A simple, fast and user-friendly alternative to 'find'"
homepage = "https://github.com/sharkdp/fd"
license = ""

[discovery]
github = "sharkdp/fd"
tag_pattern = "v{{version}}"
include_prereleases = false

[assets]
universal = false
skip_checksums = false

[assets.arm64-macos]
suffix = "aarch64-apple-darwin.tar.gz"

[assets.x86_64-macos]
suffix = "x86_64-apple-darwin.tar.gz"

[install]
bin = ["fd"]
lib = []
include = []
script = ""

[hints]
post_install = ""
