[package]
name = "helix"
description = "A post-modern modal text editor"
homepage = "https://github.com/helix-editor/helix"
license = ""

[discovery]
github = "helix-editor/helix"
tag_pattern = "v{{version}}"
include_prereleases = false

[assets]
universal = false
skip_checksums = false

[assets.arm64-macos]
suffix = "aarch64-macos.tar.xz"

[assets.x86_64-macos]
suffix = "x86_64-macos.tar.xz"

[install]
bin = ["hx"]
lib = []
include = []
script = ""

[hints]
post_install = ""
