[package]
name = "hexyl"
version = "0.16.0"
description = "A command-line hex viewer"
homepage = "https://github.com/sharkdp/hexyl"
license = ""
type = "cli"

[discovery]
github = "sharkdp/hexyl"
tag_pattern = "v{{version}}"
semver_only = true
include_prereleases = false

[assets]
url_template = "https://github.com/sharkdp/hexyl/releases/download/v{{version}}/hexyl-v{{version}}-{{target}}.tar.gz"
universal = false

[assets.targets]
arm64 = "aarch64-apple-darwin"
x86_64 = "x86_64-apple-darwin"

[checksums]
vendor_type = "sha256"
skip = true

[install]
strategy = "link"
bin = ["hexyl"]
lib = []
include = []
script = ""

[hints]
post_install = ""
