[package]
name = "charm"
version = "0.12.6"
description = "A set of tools that makes adding a backend to terminal-based applications fun and easy"
homepage = "https://github.com/charmbracelet/charm"
license = ""
type = "cli"

[discovery]
github = "charmbracelet/charm"
tag_pattern = "v{{version}}"
semver_only = true
include_prereleases = false

[assets]
url_template = "https://github.com/charmbracelet/charm/releases/download/v{{version}}/charm_{{version}}_Darwin_{{target}}.tar.gz"
universal = false

[assets.targets]
x86_64 = "x86_64"
arm64 = "arm64"

[checksums]
url_template = "https://github.com/charmbracelet/charm/releases/download/v{{version}}/checksums.txt"
vendor_type = "sha256"
skip = false

[install]
strategy = "link"
bin = ["charm"]
lib = []
include = []
script = ""

[hints]
post_install = ""
