[package]
name = "charm"
description = "A set of tools that makes adding a backend to terminal-based applications fun and easy"
homepage = "https://github.com/charmbracelet/charm"
license = ""

[discovery]
github = "charmbracelet/charm"
tag_pattern = "v{{version}}"
include_prereleases = false

[assets]
universal = false
skip_checksums = false

[assets.arm64-macos]
suffix = "darwin_arm64.tar.gz"

[assets.x86_64-macos]
suffix = "darwin_amd64.tar.gz"

[install]
bin = ["charm"]
lib = []
include = []
script = ""

[hints]
post_install = ""
