[package]
name = "choose"
description = "A human-friendly and fast alternative to cut and (sometimes) awk."
homepage = "https://github.com/theryangeary/choose"

[discovery]
github = "theryangeary/choose"
tag_pattern = "v{{version}}"

[assets]
arm64-macos = { suffix = "aarch64-apple-darwin" }
x86_64-macos = { suffix = "x86_64-apple-darwin" }

[install]
bin = ["choose"]
