[package]
name = "kitty"
description = "Cross-platform, fast, feature-rich, GPU based terminal"
homepage = "https://github.com/kovidgoyal/kitty"
license = ""

[discovery]
github = "kovidgoyal/kitty"
tag_pattern = "v{{version}}"
include_prereleases = false

[assets]
universal = false
skip_checksums = false

[assets.arm64-macos]
suffix = "darwin-arm64"

[assets.x86_64-macos]
suffix = "darwin-amd64"

[install]
bin = ["kitty"]
lib = []
include = []
script = ""

[hints]
post_install = ""
