[package]
name = "brew"
version = "5.0.8"
description = "The missing package manager for macOS (or Linux)"
homepage = "https://github.com/Homebrew/brew"
license = ""
type = "cli"

[discovery]
github = "Homebrew/brew"
tag_pattern = "{{version}}"
semver_only = true
include_prereleases = false

[assets]
url_template = "https://github.com/Homebrew/brew/releases/download/{{version}}/Homebrew-{{version}}.pkg"
universal = false

[checksums]
vendor_type = "sha256"
skip = true

[install]
strategy = "link"
bin = ["brew"]
lib = []
include = []
script = ""

[hints]
post_install = ""
