[package]
name = "broot"
description = "Balanced tree view for directories."
homepage = "https://dystroy.org/broot"

[discovery]
github = "Canop/broot"
tag_pattern = "v{{version}}"

[assets]
arm64-macos = { regex = "broot_.*_aarch64-apple-darwin\\.zip" }
x86_64-macos = { regex = "broot_.*_x86_64-apple-darwin\\.zip" }

[install]
bin = ["broot"]
