[package]
name = "pastel"
description = "A command-line tool to generate, analyze, convert and manipulate colors"
homepage = "https://github.com/sharkdp/pastel"
license = ""

[discovery]
github = "sharkdp/pastel"
tag_pattern = "v{{version}}"
include_prereleases = false

[assets]
universal = false
skip_checksums = false

[assets.x86_64-macos]
suffix = "x86_64-apple-darwin.tar.gz"

[assets.arm64-macos]
suffix = "aarch64-apple-darwin.tar.gz"

[install]
bin = ["pastel"]
lib = []
include = []
script = ""

[hints]
post_install = ""
