[package]
name = "mods"
version = "1.8.1"
description = "AI on the command line"
homepage = "https://github.com/charmbracelet/mods"
license = ""
type = "cli"

[discovery]
github = "charmbracelet/mods"
tag_pattern = "v{{version}}"
semver_only = true
include_prereleases = false

[assets]
url_template = "https://github.com/charmbracelet/mods/releases/download/v{{version}}/mods_{{version}}_Darwin_{{target}}.tar.gz"
universal = false

[assets.targets]
x86_64 = "x86_64"
arm64 = "arm64"

[checksums]
vendor_type = "sha256"
skip = false

[install]
strategy = "link"
bin = ["mods"]
lib = []
include = []
script = ""

[hints]
post_install = ""
