[package]
name = "mods"
description = "AI on the command line"
homepage = "https://github.com/charmbracelet/mods"
license = ""

[discovery]
github = "charmbracelet/mods"
tag_pattern = "v{{version}}"
include_prereleases = false

[assets]
universal = false
skip_checksums = false

[assets.x86_64-macos]
suffix = "darwin_amd64.tar.gz"

[assets.arm64-macos]
suffix = "darwin_arm64.tar.gz"

[install]
bin = ["mods"]
lib = []
include = []
script = ""

[hints]
post_install = ""
