[package]
name = "difft"
version = "0.67.0"
description = "A structural diff that understands syntax"
homepage = "https://github.com/Wilfred/difftastic"
license = ""
type = "cli"

[discovery]
github = "Wilfred/difftastic"
tag_pattern = "{{version}}"
include_prereleases = false

[assets]
url_template = "https://github.com/Wilfred/difftastic/releases/download/{{version}}/difft-{{target}}.tar.gz"
universal = false

[assets.targets]
arm64 = "aarch64-apple-darwin"
x86_64 = "x86_64-apple-darwin"

[checksums]
vendor_type = "sha256"
skip = false

[install]
strategy = "link"
bin = ["difft"]
lib = []
include = []
script = ""

[hints]
post_install = ""
