[package]
name = "difft"
description = "A structural diff that understands syntax"
homepage = "https://github.com/Wilfred/difftastic"
license = ""

[discovery]
github = "Wilfred/difftastic"
tag_pattern = "v{{version}}"
include_prereleases = false

[assets]
universal = false
skip_checksums = false

[assets.x86_64-macos]
suffix = "x86_64-apple-darwin.tar.gz"

[assets.arm64-macos]
suffix = "aarch64-apple-darwin.tar.gz"

[install]
bin = ["difft"]
lib = []
include = []
script = ""

[hints]
post_install = ""
