[package]
name = "diskus"
description = "A minimal, fast alternative to 'du -sh'"
homepage = "https://github.com/sharkdp/diskus"
license = ""

[discovery]
github = "sharkdp/diskus"
tag_pattern = "v{{version}}"
include_prereleases = false

[assets]
universal = false
skip_checksums = false

[assets.arm64-macos]
suffix = "aarch64-apple-darwin.tar.gz"

[assets.x86_64-macos]
suffix = "x86_64-apple-darwin.tar.gz"

[install]
bin = ["diskus"]
lib = []
include = []
script = ""

[hints]
post_install = ""
