[package]
name = "dive"
version = "0.13.1"
description = "A tool for exploring each layer in a Docker image"
homepage = "https://github.com/wagoodman/dive"
license = ""
type = "cli"

[discovery]
github = "wagoodman/dive"
tag_pattern = "v{{version}}"
include_prereleases = false

[assets]
url_template = "https://github.com/wagoodman/dive/releases/download/v{{version}}/dive_{{version}}_darwin_{{target}}.tar.gz"
universal = false

[assets.targets]
x86_64 = "amd64"
arm64 = "arm64"

[checksums]
url_template = "https://github.com/wagoodman/dive/releases/download/v{{version}}/dive_{{version}}_checksums.txt"
vendor_type = "sha256"
skip = false

[install]
strategy = "link"
bin = ["dive"]
lib = []
include = []
script = ""

[hints]
post_install = ""
