[package]
name = "dive"
description = "A tool for exploring each layer in a Docker image"
homepage = "https://github.com/wagoodman/dive"
license = ""

[discovery]
github = "wagoodman/dive"
tag_pattern = "v{{version}}"
include_prereleases = false

[assets]
universal = false
skip_checksums = false

[assets.arm64-macos]
suffix = "arm64.tar.gz"

[assets.x86_64-macos]
suffix = "amd64.tar.gz"

[install]
bin = ["dive"]
lib = []
include = []
script = ""

[hints]
post_install = ""
