[package]
name = "caddy"
description = "Fast and extensible multi-platform HTTP/1-2-3 web server with automatic HTTPS"
homepage = "https://github.com/caddyserver/caddy"
license = ""

[discovery]
github = "caddyserver/caddy"
tag_pattern = "v{{version}}"
include_prereleases = false

[assets]
universal = false
skip_checksums = false

[assets.x86_64-macos]
suffix = "amd64.tar.gz"

[assets.arm64-macos]
suffix = "amd64.tar.gz"

[install]
bin = ["caddy"]
lib = []
include = []
script = ""

[hints]
post_install = ""
