[package]
name = "hyperfine"
version = "1.20.0"
description = "A command-line benchmarking tool"
homepage = "https://github.com/sharkdp/hyperfine"
license = ""
type = "cli"

[discovery]
github = "sharkdp/hyperfine"
tag_pattern = "v{{version}}"
include_prereleases = false

[assets]
url_template = "https://github.com/sharkdp/hyperfine/releases/download/v{{version}}/hyperfine-v{{version}}-{{target}}.tar.gz"
universal = false

[assets.targets]
x86_64 = "x86_64-apple-darwin"
arm64 = "aarch64-apple-darwin"

[checksums]
vendor_type = "sha256"
skip = false

[install]
strategy = "link"
bin = ["hyperfine"]
lib = []
include = []
script = ""

[hints]
post_install = ""
