[package]
name = "hyperfine"
description = "A command-line benchmarking tool"
homepage = "https://github.com/sharkdp/hyperfine"
license = ""

[discovery]
github = "sharkdp/hyperfine"
tag_pattern = "v{{version}}"
include_prereleases = false

[assets]
universal = false
skip_checksums = false

[assets.x86_64-macos]
suffix = "x86_64-apple-darwin.tar.gz"

[assets.arm64-macos]
suffix = "aarch64-apple-darwin.tar.gz"

[install]
bin = ["hyperfine"]
lib = []
include = []
script = ""

[hints]
post_install = ""
