[package]
name = "railway"
description = "Railway CLI."
homepage = "https://railway.app"

[discovery]
github = "railwayapp/cli"
tag_pattern = "v{{version}}"

[assets]
arm64-macos = { suffix = "aarch64-apple-darwin.tar.gz" }
x86_64-macos = { suffix = "x86_64-apple-darwin.tar.gz" }

[install]
bin = ["railway"]
