[package]
name = "mpv"
description = "Free, open source, and cross-platform media player"
homepage = "https://github.com/mpv-player/mpv"
license = ""

[discovery]
github = "mpv-player/mpv"
tag_pattern = "v{{version}}"
include_prereleases = false

[assets]
universal = false
skip_checksums = false

[assets.arm64-macos]
regex = "mpv.*-macos.*-arm\\.zip"

[assets.x86_64-macos]
regex = "mpv.*-macos.*-x86\\.zip"

[install]
bin = ["mpv"]
lib = []
include = []
script = ""

[hints]
post_install = ""
