[package]
name = "alacritty"
version = "0.16.1"
description = ""
homepage = "https://github.com/alacritty/alacritty"
license = ""
type = "cli"

[source]
url = "https://github.com/alacritty/alacritty/releases/download/v0.16.1/Alacritty-v0.16.1.dmg"
blake3 = "4aaeee3228e90775c64c6a7d6e3418c8cd46a2c380bd2666f36651f9457809b9"
format = "dmg"
strip_components = 1

[binary.arm64]
url = "https://github.com/alacritty/alacritty/releases/download/v0.16.1/Alacritty-v0.16.1.dmg"
blake3 = "4aaeee3228e90775c64c6a7d6e3418c8cd46a2c380bd2666f36651f9457809b9"
format = "dmg"
arch = "arm64"
macos = "14.0"

[binary.x86_64]
url = "https://github.com/alacritty/alacritty/releases/download/v0.16.1/Alacritty-v0.16.1.dmg"
blake3 = "4aaeee3228e90775c64c6a7d6e3418c8cd46a2c380bd2666f36651f9457809b9"
format = "dmg"
arch = "x86_64"
macos = "14.0"

[dependencies]
runtime = []
build = []
optional = []

[install]
strategy = "link"
bin = ["alacritty"]
lib = []
include = []
script = ""

[hints]
post_install = ""
