[package]
name = "alacritty"
version = "0.16.1"
description = "A cross-platform, GPU-accelerated terminal emulator"
type = "app"

[source]
url = "https://github.com/alacritty/alacritty/releases/download/v0.16.1/Alacritty-v0.16.1.dmg"
blake3 = "4aaeee3228e90775c64c6a7d6e3418c8cd46a2c380bd2666f36651f9457809b9"
format = "dmg"

[binary.arm64]
url = "https://github.com/alacritty/alacritty/releases/download/v0.16.1/Alacritty-v0.16.1.dmg"
blake3 = "4aaeee3228e90775c64c6a7d6e3418c8cd46a2c380bd2666f36651f9457809b9"
format = "dmg"

[install]
strategy = "app"
app = "Alacritty.app"
