[package]
name = "amber"
version = "0.6.0"
description = ""
homepage = "https://github.com/dalance/amber"
license = ""
type = "cli"

[source]
url = "https://github.com/dalance/amber/releases/download/v0.6.0/amber-v0.6.0-x86_64-mac.zip"
blake3 = "bd6c435533fd4b384516e8abe0cbe6e7fadda8a78f49ee251ebf302b1740d3cd"
format = "zip"
strip_components = 1

[binary.x86_64]
url = "https://github.com/dalance/amber/releases/download/v0.6.0/amber-v0.6.0-x86_64-mac.zip"
blake3 = "bd6c435533fd4b384516e8abe0cbe6e7fadda8a78f49ee251ebf302b1740d3cd"
format = "zip"
arch = "x86_64"
macos = "14.0"

[binary.arm64]
url = "https://github.com/dalance/amber/releases/download/v0.6.0/amber-v0.6.0-x86_64-mac.zip"
blake3 = "bd6c435533fd4b384516e8abe0cbe6e7fadda8a78f49ee251ebf302b1740d3cd"
format = "zip"
arch = "arm64"
macos = "14.0"

[dependencies]
runtime = []
build = []
optional = []

[install]
strategy = "link"
bin = ["amber"]
lib = []
include = []
script = ""

[hints]
post_install = ""
