[package]
name = "argo-cd"
version = "3.2.3"
description = ""
homepage = "https://github.com/argoproj/argo-cd"
license = ""
type = "cli"

[source]
url = "https://github.com/argoproj/argo-cd/releases/download/v3.2.3/argocd-darwin-arm64"
blake3 = "6df7354ca1b3cbf29a80092bf05b452e11ca72e3342e28676c86607b95114d49"
format = "binary"
strip_components = 0

[binary.x86_64]
url = "https://github.com/argoproj/argo-cd/releases/download/v3.2.3/argocd-darwin-amd64"
blake3 = "a46eb2219202cde6125267012d1d07860a76aeced3f1e630c7eab9f3b8ad5d61"
format = "binary"
arch = "x86_64"
macos = "14.0"

[binary.arm64]
url = "https://github.com/argoproj/argo-cd/releases/download/v3.2.3/argocd-darwin-arm64"
blake3 = "6df7354ca1b3cbf29a80092bf05b452e11ca72e3342e28676c86607b95114d49"
format = "binary"
arch = "arm64"
macos = "14.0"

[dependencies]
runtime = []
build = []
optional = []

[install]
strategy = "link"
bin = ["argo-cd"]
lib = []
include = []
script = ""

[hints]
post_install = ""
