[package]
name = "asdf"
version = "0.18.0"
description = "Extendable version manager with support for Ruby, Node.js, Elixir, Erlang & more"
homepage = "https://github.com/asdf-vm/asdf"
license = ""
type = "cli"

[source]
url = "https://github.com/asdf-vm/asdf/releases/download/v0.18.0/asdf-v0.18.0-darwin-arm64.tar.gz"
blake3 = "8bfa432f471afd0b1bee3d682da3719b1777c4cb1893d438f409dad0a6c0a385"
format = "tar.gz"
strip_components = 1

[binary.x86_64]
url = "https://github.com/asdf-vm/asdf/releases/download/v0.18.0/asdf-v0.18.0-darwin-amd64.tar.gz"
blake3 = "265ef590c25d047a866aae48598dc786e87dd10f0ec97d1cefe66ef82f9bdced"
format = "tar.gz"
arch = "x86_64"
macos = "14.0"

[binary.arm64]
url = "https://github.com/asdf-vm/asdf/releases/download/v0.18.0/asdf-v0.18.0-darwin-arm64.tar.gz"
blake3 = "8bfa432f471afd0b1bee3d682da3719b1777c4cb1893d438f409dad0a6c0a385"
format = "tar.gz"
arch = "arm64"
macos = "14.0"

[dependencies]
runtime = []
build = []
optional = []

[install]
strategy = "link"
bin = ["asdf"]
lib = []
include = []
script = ""

[hints]
post_install = ""
