[package]
name = "atuin"
version = "18.10.0"
description = "Magical shell history"
homepage = "https://github.com/ellie/atuin"
license = ""
type = "cli"

[source]
url = "https://github.com/atuinsh/atuin/releases/download/v18.10.0/atuin-aarch64-apple-darwin-update"
blake3 = "0af80c9fdcb837f42568288468f002d409578a6a4901a499aa2cd1d21a4fb114"
format = "binary"
strip_components = 0

[binary.arm64]
url = "https://github.com/atuinsh/atuin/releases/download/v18.10.0/atuin-aarch64-apple-darwin-update"
blake3 = "0af80c9fdcb837f42568288468f002d409578a6a4901a499aa2cd1d21a4fb114"
format = "binary"
arch = "arm64"
macos = "14.0"

[binary.x86_64]
url = "https://github.com/atuinsh/atuin/releases/download/v18.10.0/atuin-x86_64-apple-darwin-update"
blake3 = "e23fbf423ef04da8784d1679cbb8b1cd7e1cfbb2bcc8256c1c422331939d3c19"
format = "binary"
arch = "x86_64"
macos = "14.0"

[dependencies]
runtime = []
build = []
optional = []

[install]
strategy = "link"
bin = ["atuin"]
lib = []
include = []
script = ""

[hints]
post_install = ""
