[package]
name = "aws"
version = "2.0.0dev0"
description = "Universal Command Line Interface for Amazon Web Services"
homepage = "https://github.com/aws/aws-cli"
license = ""
type = "cli"

[source]
url = "https://github.com/aws/aws-cli/releases/download/2.0.0dev0/AWS-CLI-Installer.pkg"
blake3 = "aa07e28baa5aabadb7c4df6b1c2398590a5f6d3b053a517553ba1776dc6e9830"
format = "pkg"
strip_components = 1

[binary.x86_64]
url = "https://github.com/aws/aws-cli/releases/download/2.0.0dev0/AWS-CLI-Installer.pkg"
blake3 = "aa07e28baa5aabadb7c4df6b1c2398590a5f6d3b053a517553ba1776dc6e9830"
format = "pkg"
arch = "x86_64"
macos = "14.0"

[binary.arm64]
url = "https://github.com/aws/aws-cli/releases/download/2.0.0dev0/AWS-CLI-Installer.pkg"
blake3 = "aa07e28baa5aabadb7c4df6b1c2398590a5f6d3b053a517553ba1776dc6e9830"
format = "pkg"
arch = "arm64"
macos = "14.0"

[dependencies]
runtime = []
build = []
optional = []

[install]
strategy = "link"
bin = ["aws"]
lib = []
include = []
script = ""

[hints]
post_install = ""
