[package]
name = "aws"
version = "2.0.0dev0"
description = "Universal Command Line Interface for Amazon Web Services"
homepage = "https://github.com/aws/aws-cli"
license = ""
type = "cli"

[source]
url = "https://awscli.amazonaws.com/AWSCLIV2.pkg"
blake3 = "SKIP_VERIFY" 
format = "pkg"
strip_components = 1

[binary.x86_64]
url = "https://awscli.amazonaws.com/AWSCLIV2.pkg" 
blake3 = "SKIP_VERIFY"
format = "pkg"
arch = "x86_64"
macos = "14.0"

[binary.arm64]
url = "https://awscli.amazonaws.com/AWSCLIV2.pkg"
blake3 = "SKIP_VERIFY"
format = "pkg"
arch = "arm64"
macos = "14.0"

[dependencies]
runtime = []
build = []
optional = []

[install]
strategy = "link"
bin = ["aws"]
lib = []
include = []
script = ""

[hints]
post_install = ""
