[package]
name = "bandwhich"
version = "0.23.1"
description = ""
homepage = "https://github.com/imsnif/bandwhich"
license = ""
type = "cli"

[source]
url = "https://github.com/imsnif/bandwhich/releases/download/v0.23.1/bandwhich-v0.23.1-aarch64-apple-darwin.tar.gz"
blake3 = "c0459d0c1ae591f310bc21b76c1babf378a03cf73d1f82a98d6f833aa4294584"
format = "tar.gz"
strip_components = 1

[binary.x86_64]
url = "https://github.com/imsnif/bandwhich/releases/download/v0.23.1/bandwhich-v0.23.1-x86_64-apple-darwin.tar.gz"
blake3 = "2ebb64f581c3ecaaf7394abe408c4026f6efc3a59060c1fa55b2121a9a77750a"
format = "tar.gz"
arch = "x86_64"
macos = "14.0"

[binary.arm64]
url = "https://github.com/imsnif/bandwhich/releases/download/v0.23.1/bandwhich-v0.23.1-aarch64-apple-darwin.tar.gz"
blake3 = "c0459d0c1ae591f310bc21b76c1babf378a03cf73d1f82a98d6f833aa4294584"
format = "tar.gz"
arch = "arm64"
macos = "14.0"

[dependencies]
runtime = []
build = []
optional = []

[install]
strategy = "link"
bin = ["bandwhich"]
lib = []
include = []
script = ""

[hints]
post_install = ""
