[package]
name = "brew"
version = "5.0.8"
description = ""
homepage = "https://github.com/Homebrew/brew"
license = ""
type = "cli"

[source]
url = "https://github.com/Homebrew/brew/releases/download/5.0.8/Homebrew-5.0.8.pkg"
blake3 = "fd86356b591a16aaa87e9492bee02910316a3ab114d0caf6f5bc87924e2bbe35"
format = "pkg"
strip_components = 1

[binary.arm64]
url = "https://github.com/Homebrew/brew/releases/download/5.0.8/Homebrew-5.0.8.pkg"
blake3 = "fd86356b591a16aaa87e9492bee02910316a3ab114d0caf6f5bc87924e2bbe35"
format = "pkg"
arch = "arm64"
macos = "14.0"

[binary.x86_64]
url = "https://github.com/Homebrew/brew/releases/download/5.0.8/Homebrew-5.0.8.pkg"
blake3 = "fd86356b591a16aaa87e9492bee02910316a3ab114d0caf6f5bc87924e2bbe35"
format = "pkg"
arch = "x86_64"
macos = "14.0"

[dependencies]
runtime = []
build = []
optional = []

[install]
strategy = "link"
bin = ["brew"]
lib = []
include = []
script = ""

[hints]
post_install = ""
