[package]
name = "caddy"
version = "2.10.2"
description = ""
homepage = "https://github.com/caddyserver/caddy"
license = ""
type = "cli"

[source]
url = "https://github.com/caddyserver/caddy/releases/download/v2.10.2/caddy_2.10.2_mac_amd64.tar.gz"
blake3 = "74f2aeb9a447d75b6da7b5b6de9a79f300a8a78f49ef2aab3448b77cd0eeee35"
format = "tar.gz"
strip_components = 1

[binary.x86_64]
url = "https://github.com/caddyserver/caddy/releases/download/v2.10.2/caddy_2.10.2_mac_amd64.tar.gz"
blake3 = "74f2aeb9a447d75b6da7b5b6de9a79f300a8a78f49ef2aab3448b77cd0eeee35"
format = "tar.gz"
arch = "x86_64"
macos = "14.0"

[binary.arm64]
url = "https://github.com/caddyserver/caddy/releases/download/v2.10.2/caddy_2.10.2_mac_amd64.tar.gz"
blake3 = "74f2aeb9a447d75b6da7b5b6de9a79f300a8a78f49ef2aab3448b77cd0eeee35"
format = "tar.gz"
arch = "arm64"
macos = "14.0"

[dependencies]
runtime = []
build = []
optional = []

[install]
strategy = "link"
bin = ["caddy"]
lib = []
include = []
script = ""

[hints]
post_install = ""
