[package]
name = "charm"
version = "0.12.6"
description = ""
homepage = "https://github.com/charmbracelet/charm"
license = ""
type = "cli"

[source]
url = "https://github.com/charmbracelet/charm/releases/download/v0.12.6/charm_0.12.6_Darwin_arm64.tar.gz"
blake3 = "2d15e10f0bab51294fe5f5a120a598a39f0c482672e3fe6fd8b596fa451b9fa9"
format = "tar.gz"
strip_components = 1

[binary.arm64]
url = "https://github.com/charmbracelet/charm/releases/download/v0.12.6/charm_0.12.6_Darwin_arm64.tar.gz"
blake3 = "2d15e10f0bab51294fe5f5a120a598a39f0c482672e3fe6fd8b596fa451b9fa9"
format = "tar.gz"
arch = "arm64"
macos = "14.0"

[binary.x86_64]
url = "https://github.com/charmbracelet/charm/releases/download/v0.12.6/charm_0.12.6_Darwin_x86_64.tar.gz"
blake3 = "54a0ad41cff7ec829e46a83f0cbd625ec2f38934a834baa3b52062504abb7c81"
format = "tar.gz"
arch = "x86_64"
macos = "14.0"

[dependencies]
runtime = []
build = []
optional = []

[install]
strategy = "link"
bin = ["charm"]
lib = []
include = []
script = ""

[hints]
post_install = ""
