[package]
name = "cmake"
version = "3.31.4"
description = "Cross-platform build system generator"
type = "cli"

[source]
url = "https://github.com/Kitware/CMake/releases/download/v3.31.4/cmake-3.31.4-macos-universal.tar.gz"
blake3 = "7f28fa8bc24c482ba0f40cea2f86032774946064b1875a525c0681e39fe743c1"

[binary.arm64]
url = "https://github.com/Kitware/CMake/releases/download/v3.31.4/cmake-3.31.4-macos-universal.tar.gz"
blake3 = "7f28fa8bc24c482ba0f40cea2f86032774946064b1875a525c0681e39fe743c1"

[binary.x86_64]
url = "https://github.com/Kitware/CMake/releases/download/v3.31.4/cmake-3.31.4-macos-universal.tar.gz"
blake3 = "7f28fa8bc24c482ba0f40cea2f86032774946064b1875a525c0681e39fe743c1"

[install]
bin = ["CMake.app/Contents/bin/cmake", "CMake.app/Contents/bin/ctest", "CMake.app/Contents/bin/cpack"]
