[package]
name = "cosign"
version = "3.0.3"
description = ""
homepage = "https://github.com/sigstore/cosign"
license = ""
type = "cli"

[source]
url = "https://github.com/sigstore/cosign/releases/download/v3.0.3/cosign-darwin-arm64"
blake3 = "89b399c30ebbddb368a5f8a651746698caaf0999fdd60373d419ab839d34ba49"
format = "binary"
strip_components = 0

[binary.arm64]
url = "https://github.com/sigstore/cosign/releases/download/v3.0.3/cosign-darwin-arm64"
blake3 = "89b399c30ebbddb368a5f8a651746698caaf0999fdd60373d419ab839d34ba49"
format = "binary"
arch = "arm64"
macos = "14.0"

[binary.x86_64]
url = "https://github.com/sigstore/cosign/releases/download/v3.0.3/cosign-darwin-amd64"
blake3 = "0e3c85ba674ca23aaa9dd48f3759e2e4afeaa9dd3766d04a326ce647399da1ae"
format = "binary"
arch = "x86_64"
macos = "14.0"

[dependencies]
runtime = []
build = []
optional = []

[install]
strategy = "link"
bin = ["cosign"]
lib = []
include = []
script = ""

[hints]
post_install = ""
