[package]
name = "curlie"
version = "1.8.2"
description = "The power of curl, the ease of use of httpie"
homepage = "https://github.com/rs/curlie"
license = ""
type = "cli"

[source]
url = "https://github.com/rs/curlie/releases/download/v1.8.2/curlie_1.8.2_darwin_arm64.tar.gz"
blake3 = "8aee76eced1056c790763373fa8aca2a7f29a28f7e23ea1be4989c4e908f7a7a"
format = "tar.gz"
strip_components = 1

[binary.arm64]
url = "https://github.com/rs/curlie/releases/download/v1.8.2/curlie_1.8.2_darwin_arm64.tar.gz"
blake3 = "8aee76eced1056c790763373fa8aca2a7f29a28f7e23ea1be4989c4e908f7a7a"
format = "tar.gz"
arch = "arm64"
macos = "14.0"

[binary.x86_64]
url = "https://github.com/rs/curlie/releases/download/v1.8.2/curlie_1.8.2_darwin_amd64.tar.gz"
blake3 = "ad749422e3eefa27392c23efaba9fc7ef72a26941575e1cf8aec6afd80824e63"
format = "tar.gz"
arch = "x86_64"
macos = "14.0"

[dependencies]
runtime = []
build = []
optional = []

[install]
strategy = "link"
bin = ["curlie"]
lib = []
include = []
script = ""

[hints]
post_install = ""
