[package]
name = "delta"
version = "0.18.2"
description = "A syntax-highlighting pager for git"
homepage = "https://github.com/dandavison/delta"
license = ""

[source]
url = "https://github.com/dandavison/delta/releases/download/0.18.2/delta-0.18.2-aarch64-apple-darwin.tar.gz"
blake3 = "906240593a91488ed036652a41b7b6df4852484e5bcd69e3c0a15e63dea66f89"
format = "tar.gz"
strip_components = 0

[binary.x86_64]
url = "https://github.com/dandavison/delta/releases/download/0.18.2/delta-0.18.2-x86_64-apple-darwin.tar.gz"
blake3 = "49080516fc29b7a426183c0765c9e426e959da4a8163f58208baa228d94527"
format = "tar.gz"
arch = "x86_64"
macos = "14.0"

[binary.arm64]
url = "https://github.com/dandavison/delta/releases/download/0.18.2/delta-0.18.2-aarch64-apple-darwin.tar.gz"
blake3 = "906240593a91488ed036652a41b7b6df4852484e5bcd69e3c0a15e63dea66f89"
format = "tar.gz"
arch = "arm64"
macos = "14.0"

[dependencies]
runtime = []
build = []
optional = []

[install]
strategy = "link"
bin = ["delta"]
lib = []
include = []
script = ""
