[package]
name = "delta"
version = "0.18.2"
description = ""
homepage = "https://github.com/dandavison/delta"
license = ""
type = "cli"

[source]
url = "https://github.com/dandavison/delta/releases/download/0.18.2/delta-0.18.2-aarch64-apple-darwin.tar.gz"
blake3 = "906240593a91488ed036652a41b7b6df4852484e5bcd69e3c0a15e63dea66f89"
format = "tar.gz"
strip_components = 1

[binary.arm64]
url = "https://github.com/dandavison/delta/releases/download/0.18.2/delta-0.18.2-aarch64-apple-darwin.tar.gz"
blake3 = "906240593a91488ed036652a41b7b6df4852484e5bcd69e3c0a15e63dea66f89"
format = "tar.gz"
arch = "arm64"
macos = "14.0"

[binary.x86_64]
url = "https://github.com/dandavison/delta/releases/download/0.18.2/delta-0.18.2-x86_64-apple-darwin.tar.gz"
blake3 = "ebc76b10a1255ee6498cb611c26220218db6252ccfd5b59ec27131da16b4d343"
format = "tar.gz"
arch = "x86_64"
macos = "14.0"

[dependencies]
runtime = []
build = []
optional = []

[install]
strategy = "link"
bin = ["delta"]
lib = []
include = []
script = ""

[hints]
post_install = ""
