[package]
name = "deno"
version = "2.6.3"
description = ""
homepage = "https://github.com/denoland/deno"
license = ""
type = "cli"

[source]
url = "https://github.com/denoland/deno/releases/download/v2.6.3/deno-aarch64-apple-darwin.zip"
blake3 = "e7b461cde55c33acc6a101e9e2a281a4990f3c44474093e7dc5bb86cfc9a440b"
format = "zip"
strip_components = 1

[binary.x86_64]
url = "https://github.com/denoland/deno/releases/download/v2.6.3/deno-x86_64-apple-darwin.zip"
blake3 = "d98c5bea811097583065d1718f1b82061500cc178af7a4c92d5e5be7bf131727"
format = "zip"
arch = "x86_64"
macos = "14.0"

[binary.arm64]
url = "https://github.com/denoland/deno/releases/download/v2.6.3/deno-aarch64-apple-darwin.zip"
blake3 = "e7b461cde55c33acc6a101e9e2a281a4990f3c44474093e7dc5bb86cfc9a440b"
format = "zip"
arch = "arm64"
macos = "14.0"

[dependencies]
runtime = []
build = []
optional = []

[install]
strategy = "link"
bin = ["deno"]
lib = []
include = []
script = ""

[hints]
post_install = ""
