[package]
name = "diskus"
version = "0.9.0"
description = ""
homepage = "https://github.com/sharkdp/diskus"
license = ""
type = "cli"

[source]
url = "https://github.com/sharkdp/diskus/releases/download/v0.9.0/diskus-v0.9.0-aarch64-apple-darwin.tar.gz"
blake3 = "b1c20345a7b9c3be368d36febf2f94bb8985f83a4064b8c46be8d0fcc6e03201"
format = "tar.gz"
strip_components = 1

[binary.arm64]
url = "https://github.com/sharkdp/diskus/releases/download/v0.9.0/diskus-v0.9.0-aarch64-apple-darwin.tar.gz"
blake3 = "b1c20345a7b9c3be368d36febf2f94bb8985f83a4064b8c46be8d0fcc6e03201"
format = "tar.gz"
arch = "arm64"
macos = "14.0"

[binary.x86_64]
url = "https://github.com/sharkdp/diskus/releases/download/v0.9.0/diskus-v0.9.0-x86_64-apple-darwin.tar.gz"
blake3 = "0c6eef3d9dba15e81226dc565703222a50ecde698d59c7b0fc819be511bdbec2"
format = "tar.gz"
arch = "x86_64"
macos = "14.0"

[dependencies]
runtime = []
build = []
optional = []

[install]
strategy = "link"
bin = ["diskus"]
lib = []
include = []
script = ""

[hints]
post_install = ""
