[package]
name = "duf"
version = "0.9.1"
description = "Disk Usage/Free Utility - a better 'df' alternative"
homepage = "https://github.com/muesli/duf"
license = ""
type = "cli"

[source]
url = "https://github.com/muesli/duf/releases/download/v0.9.1/duf_0.9.1_darwin_arm64.tar.gz"
blake3 = "6077fe4cc9d4c56b2caf0369c12d8e104ff6174845e6a71d3320643093b9ecff"
format = "tar.gz"
strip_components = 1

[binary.arm64]
url = "https://github.com/muesli/duf/releases/download/v0.9.1/duf_0.9.1_darwin_arm64.tar.gz"
blake3 = "6077fe4cc9d4c56b2caf0369c12d8e104ff6174845e6a71d3320643093b9ecff"
format = "tar.gz"
arch = "arm64"
macos = "14.0"

[binary.x86_64]
url = "https://github.com/muesli/duf/releases/download/v0.9.1/duf_0.9.1_darwin_x86_64.tar.gz"
blake3 = "7e31c2705e3e5f833895abc8f88b41854dbf327a2396a7b0995b81bd29d3dabb"
format = "tar.gz"
arch = "x86_64"
macos = "14.0"

[dependencies]
runtime = []
build = []
optional = []

[install]
strategy = "link"
bin = ["duf"]
lib = []
include = []
script = ""

[hints]
post_install = ""
