[package]
name = "dust"
version = "1.2.3"
description = "A more intuitive version of 'du' in Rust"
homepage = "https://github.com/bootandy/dust"
license = ""
type = "cli"

[source]
url = "https://github.com/bootandy/dust/releases/download/v1.2.3/dust-v1.2.3-aarch64-unknown-linux-gnu.tar.gz"
blake3 = "76ceee6005127a68e235a62ef385e36f54d612885ca0e3b4129a1e8095f8f0da"
format = "tar.gz"
strip_components = 1

[binary.x86_64]
url = "https://github.com/bootandy/dust/releases/download/v1.2.3/dust-v1.2.3-x86_64-apple-darwin.tar.gz"
blake3 = "5d99f423d00a680d536470433255df1cf7fca85b4572f8caeb48cf0cd29d4f21"
format = "tar.gz"
arch = "x86_64"
macos = "14.0"

[dependencies]
runtime = []
build = ["rust"]
optional = []

[build]
script = """
cargo build --release
mkdir -p $PREFIX/bin
cp target/release/dust $PREFIX/bin/
"""

[install]
strategy = "link"
bin = ["dust"]
lib = []
include = []
script = ""

[hints]
post_install = ""

