[package]
name = "etcd"
version = "3.6.7"
description = ""
homepage = "https://github.com/etcd-io/etcd"
license = ""
type = "cli"

[source]
url = "https://github.com/etcd-io/etcd/releases/download/v3.6.7/etcd-v3.6.7-darwin-arm64.zip"
blake3 = "2f910dfc11aeab74d3796cb44310cbe8673fa41d68b8d9ed0e375f52dc5e8eff"
format = "zip"
strip_components = 1

[binary.x86_64]
url = "https://github.com/etcd-io/etcd/releases/download/v3.6.7/etcd-v3.6.7-darwin-amd64.zip"
blake3 = "b39ac2083e5209da3cce0f47817db1b02c551e121f0347e83f829de6f7e930fc"
format = "zip"
arch = "x86_64"
macos = "14.0"

[binary.arm64]
url = "https://github.com/etcd-io/etcd/releases/download/v3.6.7/etcd-v3.6.7-darwin-arm64.zip"
blake3 = "2f910dfc11aeab74d3796cb44310cbe8673fa41d68b8d9ed0e375f52dc5e8eff"
format = "zip"
arch = "arm64"
macos = "14.0"

[dependencies]
runtime = []
build = []
optional = []

[install]
strategy = "link"
bin = ["etcd"]
lib = []
include = []
script = ""

[hints]
post_install = ""
