[package]
name = "eza"
version = "0.23.4"
description = "A modern replacement for ls"
homepage = "https://github.com/eza-community/eza"
license = "MIT"
type = "cli"

[source]
url = "https://github.com/eza-community/eza/archive/refs/tags/v0.23.4.tar.gz"
blake3 = "7320e161a48dbd896101bc1bd308c5f92ca8c8cc171344571463c3045b7737da"
format = "tar.gz"
strip_components = 1

[dependencies]
runtime = []
build = ["rust", "pandoc"]
optional = []

[build]
script = """
cargo build --release
mkdir -p $PREFIX/bin
cp target/release/eza $PREFIX/bin/
"""

[install]
strategy = "link"
bin = ["eza"]
lib = []
include = []
script = ""

[hints]
post_install = ""
