[package]
name = "fastfetch"
version = "2.56.1"
description = "A maintained, feature-rich and performance oriented, neofetch like system information tool"
homepage = "https://github.com/fastfetch-cli/fastfetch"
license = ""
type = "cli"

[source]
url = "https://github.com/fastfetch-cli/fastfetch/releases/download/2.56.1/fastfetch-macos-aarch64.tar.gz"
blake3 = "b980f173b35ad873e6b1ae73b8284b62a4e632032484ba803f813edb1e01225d"
format = "tar.gz"
strip_components = 1

[binary.arm64]
url = "https://github.com/fastfetch-cli/fastfetch/releases/download/2.56.1/fastfetch-macos-aarch64.tar.gz"
blake3 = "b980f173b35ad873e6b1ae73b8284b62a4e632032484ba803f813edb1e01225d"
format = "tar.gz"
arch = "arm64"
macos = "14.0"

[binary.x86_64]
url = "https://github.com/fastfetch-cli/fastfetch/releases/download/2.56.1/fastfetch-macos-amd64.tar.gz"
blake3 = "6a0d73c99f3eb5504aa7a6a9a252806b004f7320bc3e9e924557b5865e89701f"
format = "tar.gz"
arch = "x86_64"
macos = "14.0"

[dependencies]
runtime = []
build = []
optional = []

[install]
strategy = "link"
bin = ["fastfetch"]
lib = []
include = []
script = ""

[hints]
post_install = ""
