[package]
name = "fastfetch"
version = "2.56.1"
description = "A maintained, feature-rich and performance oriented, system information tool"
type = "cli"

[source]
url = "https://github.com/fastfetch-cli/fastfetch/releases/download/2.56.1/fastfetch-macos-aarch64.tar.gz"
blake3 = "b980f173b35ad873e6b1ae73b8284b62a4e632032484ba803f813edb1e01225d"
format = "tar.gz"

[binary.arm64]
url = "https://github.com/fastfetch-cli/fastfetch/releases/download/2.56.1/fastfetch-macos-aarch64.tar.gz"
blake3 = "b980f173b35ad873e6b1ae73b8284b62a4e632032484ba803f813edb1e01225d"
format = "tar.gz"

[install]
strategy = "link"
bin = ["fastfetch-macos-universal/usr/bin/fastfetch:fastfetch"]
