[package]
name = "fd"
version = "10.3.0"
description = "A simple, fast and user-friendly alternative to 'find'"
homepage = "https://github.com/sharkdp/fd"
license = ""
type = "cli"

[source]
url = "https://github.com/sharkdp/fd/releases/download/v10.3.0/fd-v10.3.0-aarch64-apple-darwin.tar.gz"
blake3 = "e7a554aed4fea189f2aa297e82087ceaebb844eac55a2503e5321cce88fbb636"
format = "tar.gz"
strip_components = 1

[binary.x86_64]
url = "https://github.com/sharkdp/fd/releases/download/v10.3.0/fd-v10.3.0-x86_64-apple-darwin.tar.gz"
blake3 = "cb70341c023d1ad8d44bbaa5e3f9a06249554099cbd4fbe602339a4ff8f09f18"
format = "tar.gz"
arch = "x86_64"
macos = "14.0"

[binary.arm64]
url = "https://github.com/sharkdp/fd/releases/download/v10.3.0/fd-v10.3.0-aarch64-apple-darwin.tar.gz"
blake3 = "e7a554aed4fea189f2aa297e82087ceaebb844eac55a2503e5321cce88fbb636"
format = "tar.gz"
arch = "arm64"
macos = "14.0"

[dependencies]
runtime = []
build = []
optional = []

[install]
strategy = "link"
bin = ["fd"]
lib = []
include = []
script = ""

[hints]
post_install = ""
