[package]
name = "fd"
version = "10.3.0"
description = ""
homepage = ""
license = ""
type = "cli"

[source]
url = "https://github.com/sharkdp/fd/releases/download/v10.3.0/fd-v10.3.0-aarch64-apple-darwin.tar.gz"
blake3 = "e7a554aed4fea189f2aa297e82087ceaebb844eac55a2503e5321cce88fbb636"
format = "tar.gz"
strip_components = 1

[binary.arm64]
url = "https://github.com/sharkdp/fd/releases/download/v10.3.0/fd-v10.3.0-aarch64-apple-darwin.tar.gz"
blake3 = "e7a554aed4fea189f2aa297e82087ceaebb844eac55a2503e5321cce88fbb636"
format = "tar.gz"

[dependencies]
runtime = []
build = []
optional = []

[install]
strategy = "link"
bin = ["fd"]

[hints]
post_install = ""
