[package]
name = "fx"
version = "39.2.0"
description = "Terminal JSON viewer & processor"
homepage = "https://github.com/antonmedv/fx"
license = ""
type = "cli"

[source]
url = "https://github.com/antonmedv/fx/releases/download/39.2.0/fx_darwin_arm64"
blake3 = "2687dd6b3829bf024f5dbdda42bc58479e3a995efe4f8fc921627a7d0f5240f6"
format = "binary"
strip_components = 0

[binary.arm64]
url = "https://github.com/antonmedv/fx/releases/download/39.2.0/fx_darwin_arm64"
blake3 = "2687dd6b3829bf024f5dbdda42bc58479e3a995efe4f8fc921627a7d0f5240f6"
format = "binary"
arch = "arm64"
macos = "14.0"

[binary.x86_64]
url = "https://github.com/antonmedv/fx/releases/download/39.2.0/fx_darwin_amd64"
blake3 = "e26b4dc4a0efea9513a7073658db1e8442d44cdd44159ccd7e7016a6a7676cdf"
format = "binary"
arch = "x86_64"
macos = "14.0"

[dependencies]
runtime = []
build = []
optional = []

[install]
strategy = "link"
bin = ["fx"]
lib = []
include = []
script = ""

[hints]
post_install = ""
