[package]
name = "fzf"
version = "0.67.0"
description = "A command-line fuzzy finder"
homepage = "https://github.com/junegunn/fzf"
license = "MIT"
type = "cli"

[source]
url = "https://github.com/junegunn/fzf/releases/download/v0.67.0/fzf-0.67.0-darwin_arm64.tar.gz"
blake3 = ""
strip_components = 0

[binary]

[dependencies]
runtime = []
build = []
optional = []

[install]
bin = ["fzf"]

[hints]
post_install = ""
