[package]
name = "fzf"
version = "0.67.0"
description = "A command-line fuzzy finder"
homepage = "https://github.com/junegunn/fzf"
license = ""
type = "cli"

[source]
url = "https://github.com/junegunn/fzf/releases/download/v0.67.0/fzf-0.67.0-darwin_arm64.tar.gz"
blake3 = "656a37e09d1f5fef45801debb60e609c5cf0bef8e822e1f1a89fc2ab4e399310"
format = "tar.gz"
strip_components = 1

[binary.arm64]
url = "https://github.com/junegunn/fzf/releases/download/v0.67.0/fzf-0.67.0-darwin_arm64.tar.gz"
blake3 = "656a37e09d1f5fef45801debb60e609c5cf0bef8e822e1f1a89fc2ab4e399310"
format = "tar.gz"
arch = "arm64"
macos = "14.0"

[binary.x86_64]
url = "https://github.com/junegunn/fzf/releases/download/v0.67.0/fzf-0.67.0-darwin_amd64.tar.gz"
blake3 = "6d38a15a92cb24334d138be1699ba7f9059804295e9cfb317414c06477e622fc"
format = "tar.gz"
arch = "x86_64"
macos = "14.0"

[dependencies]
runtime = []
build = []
optional = []

[install]
strategy = "link"
bin = ["fzf"]
lib = []
include = []
script = ""

[hints]
post_install = ""
