[package]
name = "gh"
version = "0.0.0"
description = ""
homepage = ""
license = ""
type = "cli"

[source]
url = "https://github.com/cli/cli"
blake3 = ""
strip_components = 1

[binary]

[dependencies]
runtime = []
build = []
optional = []

[install]
bin = ["gh"]

[hints]
post_install = ""
