[package]
name = "gh"
version = "2.83.2"
description = ""
homepage = "https://github.com/cli/cli"
license = ""
type = "cli"

[source]
url = "https://github.com/cli/cli/releases/download/v2.83.2/gh_2.83.2_macOS_arm64.zip"
blake3 = "7822d101eed0c4655f55ea502b4993626829c90edb99ba32ae6d9c51411757b0"
format = "zip"
strip_components = 1

[binary.x86_64]
url = "https://github.com/cli/cli/releases/download/v2.83.2/gh_2.83.2_macOS_universal.pkg"
blake3 = "ef7845520d19cfd2c4ea0ef9243a4268e51a33238901caf45e24f84f6ad6d8dc"
format = "zip"
arch = "x86_64"
macos = "14.0"

[binary.arm64]
url = "https://github.com/cli/cli/releases/download/v2.83.2/gh_2.83.2_macOS_arm64.zip"
blake3 = "7822d101eed0c4655f55ea502b4993626829c90edb99ba32ae6d9c51411757b0"
format = "zip"
arch = "arm64"
macos = "14.0"

[dependencies]
runtime = []
build = []
optional = []

[install]
strategy = "link"
bin = ["gh"]
lib = []
include = []
script = ""

[hints]
post_install = ""
