[package]
name = "ghostty"
version = "tip"
description = ""
homepage = "https://github.com/ghostty-org/ghostty"
license = ""
type = "cli"

[source]
url = "https://github.com/ghostty-org/ghostty/releases/download/tip/Ghostty.dmg"
blake3 = "52932f9baa7b13cf7c265b2b2ae3b319d1c16d8d7c3fca554e2616d2e7763186"
format = "dmg"
strip_components = 1

[binary.arm64]
url = "https://github.com/ghostty-org/ghostty/releases/download/tip/Ghostty.dmg"
blake3 = "52932f9baa7b13cf7c265b2b2ae3b319d1c16d8d7c3fca554e2616d2e7763186"
format = "dmg"
arch = "arm64"
macos = "14.0"

[binary.x86_64]
url = "https://github.com/ghostty-org/ghostty/releases/download/tip/Ghostty.dmg"
blake3 = "52932f9baa7b13cf7c265b2b2ae3b319d1c16d8d7c3fca554e2616d2e7763186"
format = "dmg"
arch = "x86_64"
macos = "14.0"

[dependencies]
runtime = []
build = []
optional = []

[install]
strategy = "link"
bin = ["ghostty"]
lib = []
include = []
script = ""

[hints]
post_install = ""
