[package]
name = "ghostty"
version = "1.2.3"
description = "A fast, feature-rich, GPU-accelerated terminal emulator"
homepage = "https://github.com/ghostty-org/ghostty"
license = ""
type = "cli"

[source]
url = "https://release.files.ghostty.org/1.2.3/Ghostty.dmg"
blake3 = "59f2584d0aaadc595ece8742f9c5a806c10ebd330b51a352748ad2305044d49b"
format = "dmg"
strip_components = 1

[binary.arm64]
url = "https://release.files.ghostty.org/1.2.3/Ghostty.dmg"
blake3 = "59f2584d0aaadc595ece8742f9c5a806c10ebd330b51a352748ad2305044d49b"
format = "dmg"
arch = "arm64"
macos = "14.0"

[binary.x86_64]
url = "https://release.files.ghostty.org/1.2.3/Ghostty.dmg"
blake3 = "59f2584d0aaadc595ece8742f9c5a806c10ebd330b51a352748ad2305044d49b"
format = "dmg"
arch = "x86_64"
macos = "14.0"

[dependencies]
runtime = []
build = []
optional = []

[install]
strategy = "link"
bin = ["ghostty"]
lib = []
include = []
script = ""

[hints]
post_install = ""
