[package]
name = "git-lfs"
version = "3.7.1"
description = "Git extension for versioning large files"
homepage = "https://github.com/git-lfs/git-lfs"
license = ""
type = "cli"

[source]
url = "https://github.com/git-lfs/git-lfs/releases/download/v3.7.1/git-lfs-darwin-arm64-v3.7.1.zip"
blake3 = "979501ac3ed205320f79cd4fb8a6c208c1d3d3287c6567d5d485f644a72a2ef0"
format = "zip"
strip_components = 1

[binary.arm64]
url = "https://github.com/git-lfs/git-lfs/releases/download/v3.7.1/git-lfs-darwin-arm64-v3.7.1.zip"
blake3 = "979501ac3ed205320f79cd4fb8a6c208c1d3d3287c6567d5d485f644a72a2ef0"
format = "zip"
arch = "arm64"
macos = "14.0"

[binary.x86_64]
url = "https://github.com/git-lfs/git-lfs/releases/download/v3.7.1/git-lfs-darwin-amd64-v3.7.1.zip"
blake3 = "f247afd33d927f6a6f6fd969f086389cc409ad7d55176625948d2d456852048a"
format = "zip"
arch = "x86_64"
macos = "14.0"

[dependencies]
runtime = []
build = []
optional = []

[install]
strategy = "link"
bin = ["git-lfs"]
lib = []
include = []
script = ""

[hints]
post_install = ""
