[package]
name = "gitui"
version = "0.28.0"
description = ""
homepage = "https://github.com/extrawurst/gitui"
license = ""
type = "cli"

[source]
url = "https://github.com/gitui-org/gitui/releases/download/v0.28.0/gitui-mac-x86.tar.gz"
blake3 = "52f1377dd3ba868fd397ba223bcc7736db89f8c41a35bd0c3f9553580c666efa"
format = "tar.gz"
strip_components = 1

[binary.x86_64]
url = "https://github.com/gitui-org/gitui/releases/download/v0.28.0/gitui-mac-x86.tar.gz"
blake3 = "52f1377dd3ba868fd397ba223bcc7736db89f8c41a35bd0c3f9553580c666efa"
format = "tar.gz"
arch = "x86_64"
macos = "14.0"

[binary.arm64]
url = "https://github.com/gitui-org/gitui/releases/download/v0.28.0/gitui-mac-x86.tar.gz"
blake3 = "52f1377dd3ba868fd397ba223bcc7736db89f8c41a35bd0c3f9553580c666efa"
format = "tar.gz"
arch = "arm64"
macos = "14.0"

[dependencies]
runtime = []
build = []
optional = []

[install]
strategy = "link"
bin = ["gitui"]
lib = []
include = []
script = ""

[hints]
post_install = ""
