[package]
name = "glab"
version = "1.22.0"
description = "A GitLab CLI tool"
homepage = "https://github.com/profclems/glab"
license = ""
type = "cli"

[source]
url = "https://github.com/profclems/glab/releases/download/v1.22.0/glab_1.22.0_macOS_x86_64.tar.gz"
blake3 = "ed84440826cd77a73efcb806b95acfa66fa59847f53a312aaafdc29ddc5bf747"
format = "tar.gz"
strip_components = 1

[binary.arm64]
url = "https://github.com/profclems/glab/releases/download/v1.22.0/glab_1.22.0_macOS_x86_64.tar.gz"
blake3 = "ed84440826cd77a73efcb806b95acfa66fa59847f53a312aaafdc29ddc5bf747"
format = "tar.gz"
arch = "arm64"
macos = "14.0"

[binary.x86_64]
url = "https://github.com/profclems/glab/releases/download/v1.22.0/glab_1.22.0_macOS_x86_64.tar.gz"
blake3 = "ed84440826cd77a73efcb806b95acfa66fa59847f53a312aaafdc29ddc5bf747"
format = "tar.gz"
arch = "x86_64"
macos = "14.0"

[dependencies]
runtime = []
build = []
optional = []

[install]
strategy = "link"
bin = ["glab"]
lib = []
include = []
script = ""

[hints]
post_install = ""
