[package]
name = "golangci-lint"
version = "2.7.2"
description = ""
homepage = "https://github.com/golangci/golangci-lint"
license = ""
type = "cli"

[source]
url = "https://github.com/golangci/golangci-lint/releases/download/v2.7.2/golangci-lint-2.7.2-darwin-arm64.tar.gz"
blake3 = "6b20dfc465b9460eddd3aa1d9380972cb1512b261264ce6b455055088cd72586"
format = "tar.gz"
strip_components = 1

[binary.arm64]
url = "https://github.com/golangci/golangci-lint/releases/download/v2.7.2/golangci-lint-2.7.2-darwin-arm64.tar.gz"
blake3 = "6b20dfc465b9460eddd3aa1d9380972cb1512b261264ce6b455055088cd72586"
format = "tar.gz"
arch = "arm64"
macos = "14.0"

[binary.x86_64]
url = "https://github.com/golangci/golangci-lint/releases/download/v2.7.2/golangci-lint-2.7.2-darwin-amd64.tar.gz"
blake3 = "15eaf0013a6be7b20474765c21e3d12385c93ef9fd672a7f2304391592822795"
format = "tar.gz"
arch = "x86_64"
macos = "14.0"

[dependencies]
runtime = []
build = []
optional = []

[install]
strategy = "link"
bin = ["golangci-lint"]
lib = []
include = []
script = ""

[hints]
post_install = ""
