[package]
name = "goreleaser"
version = "2.13.2"
description = "Release engineering, simplified"
homepage = "https://github.com/goreleaser/goreleaser"
license = ""
type = "cli"

[source]
url = "https://github.com/goreleaser/goreleaser/releases/download/v2.13.2/goreleaser_Darwin_arm64.tar.gz"
blake3 = "00c357145f9aa74635e09d076b1af468fa6d50e1465ebbc20b7571b0e600feaf"
format = "tar.gz"
strip_components = 1

[binary.x86_64]
url = "https://github.com/goreleaser/goreleaser/releases/download/v2.13.2/goreleaser_Darwin_x86_64.tar.gz"
blake3 = "7085b460b6610aabbcce6d453bc4eeceb2e7ec9ca3364549799ca262cfd3510f"
format = "tar.gz"
arch = "x86_64"
macos = "14.0"

[binary.arm64]
url = "https://github.com/goreleaser/goreleaser/releases/download/v2.13.2/goreleaser_Darwin_arm64.tar.gz"
blake3 = "00c357145f9aa74635e09d076b1af468fa6d50e1465ebbc20b7571b0e600feaf"
format = "tar.gz"
arch = "arm64"
macos = "14.0"

[dependencies]
runtime = []
build = []
optional = []

[install]
strategy = "link"
bin = ["goreleaser"]
lib = []
include = []
script = ""

[hints]
post_install = ""
