[package]
name = "gping"
version = "1.20.1"
description = "Ping, but with a graph"
homepage = "https://github.com/orf/gping"
license = ""
type = "cli"

[source]
url = "https://github.com/orf/gping/releases/download/gping-v1.20.1/gping-macOS-arm64.tar.gz"
blake3 = "f978da8f6b0e9693c3f454ac2348af7e809b934d33be599437c50504c5f58232"
format = "tar.gz"
strip_components = 1

[binary.x86_64]
url = "https://github.com/orf/gping/releases/download/gping-v1.20.1/gping-macOS-x86_64.tar.gz"
blake3 = "16c05d37a0bb6ee6b85508999e4a9cbb0bc0996439d010caf468e1e43aaa6e37"
format = "tar.gz"
arch = "x86_64"
macos = "14.0"

[binary.arm64]
url = "https://github.com/orf/gping/releases/download/gping-v1.20.1/gping-macOS-arm64.tar.gz"
blake3 = "f978da8f6b0e9693c3f454ac2348af7e809b934d33be599437c50504c5f58232"
format = "tar.gz"
arch = "arm64"
macos = "14.0"

[dependencies]
runtime = []
build = []
optional = []

[install]
strategy = "link"
bin = ["gping"]
lib = []
include = []
script = ""

[hints]
post_install = ""
