[package]
name = "grex"
version = "1.4.6"
description = ""
homepage = "https://github.com/pemistahl/grex"
license = ""
type = "cli"

[source]
url = "https://github.com/pemistahl/grex/releases/download/v1.4.6/grex-v1.4.6-aarch64-apple-darwin.tar.gz"
blake3 = "d2e840ed20e7755aba47c1dfebf00080cfe526f052421e08f3d77c116c5b5c9e"
format = "tar.gz"
strip_components = 1

[binary.arm64]
url = "https://github.com/pemistahl/grex/releases/download/v1.4.6/grex-v1.4.6-aarch64-apple-darwin.tar.gz"
blake3 = "d2e840ed20e7755aba47c1dfebf00080cfe526f052421e08f3d77c116c5b5c9e"
format = "tar.gz"
arch = "arm64"
macos = "14.0"

[binary.x86_64]
url = "https://github.com/pemistahl/grex/releases/download/v1.4.6/grex-v1.4.6-x86_64-apple-darwin.tar.gz"
blake3 = "a546e4d08cf3ee300eac352e96d0aaa24edb5da29fe82e8692c76ad69f0e1781"
format = "tar.gz"
arch = "x86_64"
macos = "14.0"

[dependencies]
runtime = []
build = []
optional = []

[install]
strategy = "link"
bin = ["grex"]
lib = []
include = []
script = ""

[hints]
post_install = ""
