[package]
name = "hx"
version = "25.07.1"
description = "A post-modern modal text editor"
homepage = "https://github.com/helix-editor/helix"
license = ""
type = "cli"

[source]
url = "https://github.com/helix-editor/helix/releases/download/25.07.1/helix-25.07.1-aarch64-macos.tar.xz"
blake3 = "41aec30515e981bc97a7037bf24e4d9e03bb8afd7d782f98844a318db14bd1dc"
format = "tar"
strip_components = 1

[binary.x86_64]
url = "https://github.com/helix-editor/helix/releases/download/25.07.1/helix-25.07.1-aarch64-macos.tar.xz"
blake3 = "41aec30515e981bc97a7037bf24e4d9e03bb8afd7d782f98844a318db14bd1dc"
format = "tar"
arch = "x86_64"
macos = "14.0"

[binary.arm64]
url = "https://github.com/helix-editor/helix/releases/download/25.07.1/helix-25.07.1-aarch64-macos.tar.xz"
blake3 = "41aec30515e981bc97a7037bf24e4d9e03bb8afd7d782f98844a318db14bd1dc"
format = "tar"
arch = "arm64"
macos = "14.0"

[dependencies]
runtime = []
build = []
optional = []

[install]
strategy = "link"
bin = ["hx"]
lib = []
include = []
script = ""

[hints]
post_install = ""
