[package]
name = "hyperfine"
version = "1.20.0"
description = "A command-line benchmarking tool"
type = "cli"

[source]
url = "https://github.com/sharkdp/hyperfine/releases/download/v1.20.0/hyperfine-v1.20.0-aarch64-apple-darwin.tar.gz"
blake3 = "706b2ffad225abe3bbe290e942e69116dce94ecc3dc9046a5bd6168501695658"

[binary.arm64]
url = "https://github.com/sharkdp/hyperfine/releases/download/v1.20.0/hyperfine-v1.20.0-aarch64-apple-darwin.tar.gz"
blake3 = "706b2ffad225abe3bbe290e942e69116dce94ecc3dc9046a5bd6168501695658"

[install]
bin = ["hyperfine"]
