[package]
name = "hyperfine"
version = "1.20.0"
description = ""
homepage = "https://github.com/sharkdp/hyperfine"
license = ""
type = "cli"

[source]
url = "https://github.com/sharkdp/hyperfine/releases/download/v1.20.0/hyperfine-v1.20.0-aarch64-apple-darwin.tar.gz"
blake3 = "706b2ffad225abe3bbe290e942e69116dce94ecc3dc9046a5bd6168501695658"
format = "tar.gz"
strip_components = 1

[binary.x86_64]
url = "https://github.com/sharkdp/hyperfine/releases/download/v1.20.0/hyperfine-v1.20.0-x86_64-apple-darwin.tar.gz"
blake3 = "394b91415899a0a31dd14c74c2de386eac9dd8643a184c5195d4ea738cf1a6c7"
format = "tar.gz"
arch = "x86_64"
macos = "14.0"

[binary.arm64]
url = "https://github.com/sharkdp/hyperfine/releases/download/v1.20.0/hyperfine-v1.20.0-aarch64-apple-darwin.tar.gz"
blake3 = "706b2ffad225abe3bbe290e942e69116dce94ecc3dc9046a5bd6168501695658"
format = "tar.gz"
arch = "arm64"
macos = "14.0"

[dependencies]
runtime = []
build = []
optional = []

[install]
strategy = "link"
bin = ["hyperfine"]
lib = []
include = []
script = ""

[hints]
post_install = ""
