[package]
name = "jq"
version = "0.0.0"
description = ""
homepage = ""
license = ""
type = "cli"

[source]
url = "https://github.com/jqlang/jq"
blake3 = ""
strip_components = 1

[binary]

[dependencies]
runtime = []
build = []
optional = []

[install]
bin = ["jq"]

[hints]
post_install = ""
