[package]
name = "just"
version = "1.45.0"
description = "Just a command runner"
homepage = "https://github.com/casey/just"
license = ""
type = "cli"

[source]
url = "https://github.com/casey/just/releases/download/1.45.0/just-1.45.0-aarch64-apple-darwin.tar.gz"
blake3 = "61ece874cb86d7c17a5930f9f2d3405a277907faabddc7dae6e0342191c1af0c"
format = "tar.gz"
strip_components = 1

[binary.x86_64]
url = "https://github.com/casey/just/releases/download/1.45.0/just-1.45.0-x86_64-apple-darwin.tar.gz"
blake3 = "af9a88712a184517cb800416322af41e4167ba72db285492c7772189ffc97a1c"
format = "tar.gz"
arch = "x86_64"
macos = "14.0"

[binary.arm64]
url = "https://github.com/casey/just/releases/download/1.45.0/just-1.45.0-aarch64-apple-darwin.tar.gz"
blake3 = "61ece874cb86d7c17a5930f9f2d3405a277907faabddc7dae6e0342191c1af0c"
format = "tar.gz"
arch = "arm64"
macos = "14.0"

[dependencies]
runtime = []
build = []
optional = []

[install]
strategy = "link"
bin = ["just"]
lib = []
include = []
script = ""

[hints]
post_install = ""
