[package]
name = "lazydocker"
version = "0.24.3"
description = ""
homepage = "https://github.com/jesseduffield/lazydocker"
license = ""
type = "cli"

[source]
url = "https://github.com/jesseduffield/lazydocker/releases/download/v0.24.3/lazydocker_0.24.3_Darwin_arm64.tar.gz"
blake3 = "e0e3a6865ee7f0b146be79b3625ff7c072e07782f81840d01db9df0ca926a823"
format = "tar.gz"
strip_components = 1

[binary.arm64]
url = "https://github.com/jesseduffield/lazydocker/releases/download/v0.24.3/lazydocker_0.24.3_Darwin_arm64.tar.gz"
blake3 = "e0e3a6865ee7f0b146be79b3625ff7c072e07782f81840d01db9df0ca926a823"
format = "tar.gz"
arch = "arm64"
macos = "14.0"

[binary.x86_64]
url = "https://github.com/jesseduffield/lazydocker/releases/download/v0.24.3/lazydocker_0.24.3_Darwin_x86_64.tar.gz"
blake3 = "82fe4bfea47cc652c00fa9a93e8c6de1154c8eadaa9c04ae002a6a77eb22da85"
format = "tar.gz"
arch = "x86_64"
macos = "14.0"

[dependencies]
runtime = []
build = []
optional = []

[install]
strategy = "link"
bin = ["lazydocker"]
lib = []
include = []
script = ""

[hints]
post_install = ""
