[package]
name = "lazygit"
version = "0.57.0"
description = "Simple terminal UI for git commands"
homepage = "https://github.com/jesseduffield/lazygit"
license = ""
type = "cli"

[source]
url = "https://github.com/jesseduffield/lazygit/releases/download/v0.57.0/lazygit_0.57.0_darwin_arm64.tar.gz"
blake3 = "5e7a34f0465ee0108203c14277841f15299a83a0f9afc4f0aa66488ba5ff4392"
format = "tar.gz"
strip_components = 1

[binary.arm64]
url = "https://github.com/jesseduffield/lazygit/releases/download/v0.57.0/lazygit_0.57.0_darwin_arm64.tar.gz"
blake3 = "5e7a34f0465ee0108203c14277841f15299a83a0f9afc4f0aa66488ba5ff4392"
format = "tar.gz"
arch = "arm64"
macos = "14.0"

[binary.x86_64]
url = "https://github.com/jesseduffield/lazygit/releases/download/v0.57.0/lazygit_0.57.0_darwin_x86_64.tar.gz"
blake3 = "cf88d689e6cf7f10d1165e3f41b4b892b5a8793cc29bf9c9c942937757f427da"
format = "tar.gz"
arch = "x86_64"
macos = "14.0"

[dependencies]
runtime = []
build = []
optional = []

[install]
strategy = "link"
bin = ["lazygit"]
lib = []
include = []
script = ""

[hints]
post_install = ""
