[package]
name = "marp"
version = "4.2.3"
description = "CLI interface for Marp and Marpit-based converters"
homepage = "https://github.com/marp-team/marp-cli"
license = ""
type = "cli"

[source]
url = "https://github.com/marp-team/marp-cli/releases/download/v4.2.3/marp-cli-v4.2.3-mac.tar.gz"
blake3 = "e4b01344b97616cd59effc2cb0787bea4728f08fe8e0581a3061352b2d816775"
format = "tar.gz"
strip_components = 1

[binary.arm64]
url = "https://github.com/marp-team/marp-cli/releases/download/v4.2.3/marp-cli-v4.2.3-mac.tar.gz"
blake3 = "e4b01344b97616cd59effc2cb0787bea4728f08fe8e0581a3061352b2d816775"
format = "tar.gz"
arch = "arm64"
macos = "14.0"

[binary.x86_64]
url = "https://github.com/marp-team/marp-cli/releases/download/v4.2.3/marp-cli-v4.2.3-mac.tar.gz"
blake3 = "e4b01344b97616cd59effc2cb0787bea4728f08fe8e0581a3061352b2d816775"
format = "tar.gz"
arch = "x86_64"
macos = "14.0"

[dependencies]
runtime = []
build = []
optional = []

[install]
strategy = "link"
bin = ["marp"]
lib = []
include = []
script = ""

[hints]
post_install = ""
