[package]
name = "micro"
version = "2.0.15"
description = ""
homepage = "https://github.com/zyedidia/micro"
license = ""
type = "cli"

[source]
url = "https://github.com/zyedidia/micro/releases/download/v2.0.15/micro-2.0.15-macos-arm64.tar.gz"
blake3 = "d2070c6e8208fdd500cef49490ac87a067dfda80100ff47854c3544cdac616a9"
format = "tar.gz"
strip_components = 1

[binary.arm64]
url = "https://github.com/zyedidia/micro/releases/download/v2.0.15/micro-2.0.15-macos-arm64.tar.gz"
blake3 = "d2070c6e8208fdd500cef49490ac87a067dfda80100ff47854c3544cdac616a9"
format = "tar.gz"
arch = "arm64"
macos = "14.0"

[binary.x86_64]
url = "https://github.com/zyedidia/micro/releases/download/v2.0.15/micro-2.0.15-macos-arm64.tar.gz"
blake3 = "d2070c6e8208fdd500cef49490ac87a067dfda80100ff47854c3544cdac616a9"
format = "tar.gz"
arch = "x86_64"
macos = "14.0"

[dependencies]
runtime = []
build = []
optional = []

[install]
strategy = "link"
bin = ["micro"]
lib = []
include = []
script = ""

[hints]
post_install = ""
