[package]
name = "migrate"
version = "4.19.1"
description = "Database migrations tool"
homepage = "https://github.com/golang-migrate/migrate"
license = ""
type = "cli"

[source]
url = "https://github.com/golang-migrate/migrate/releases/download/v4.19.1/migrate.darwin-arm64.tar.gz"
blake3 = "1671ffb1003fc850c426011a121ac25990152955d7b4ed582eabd9b3a7a593b5"
format = "tar.gz"
strip_components = 1

[binary.arm64]
url = "https://github.com/golang-migrate/migrate/releases/download/v4.19.1/migrate.darwin-arm64.tar.gz"
blake3 = "1671ffb1003fc850c426011a121ac25990152955d7b4ed582eabd9b3a7a593b5"
format = "tar.gz"
arch = "arm64"
macos = "14.0"

[binary.x86_64]
url = "https://github.com/golang-migrate/migrate/releases/download/v4.19.1/migrate.darwin-amd64.tar.gz"
blake3 = "b8d8f9d7f8f7641bdcf40e3687fb1d7ff977f01e8faf053e1ff5500e01ec0956"
format = "tar.gz"
arch = "x86_64"
macos = "14.0"

[dependencies]
runtime = []
build = []
optional = []

[install]
strategy = "link"
bin = ["migrate"]
lib = []
include = []
script = ""

[hints]
post_install = ""
