[package]
name = "mods"
version = "1.8.1"
description = ""
homepage = "https://github.com/charmbracelet/mods"
license = ""
type = "cli"

[source]
url = "https://github.com/charmbracelet/mods/releases/download/v1.8.1/mods_1.8.1_Darwin_arm64.tar.gz"
blake3 = "73f57187872a26acdacad0636afa65a41f0aa03eb087d66369759d9e066c21a2"
format = "tar.gz"
strip_components = 1

[binary.arm64]
url = "https://github.com/charmbracelet/mods/releases/download/v1.8.1/mods_1.8.1_Darwin_arm64.tar.gz"
blake3 = "73f57187872a26acdacad0636afa65a41f0aa03eb087d66369759d9e066c21a2"
format = "tar.gz"
arch = "arm64"
macos = "14.0"

[binary.x86_64]
url = "https://github.com/charmbracelet/mods/releases/download/v1.8.1/mods_1.8.1_Darwin_x86_64.tar.gz"
blake3 = "e72f5d9346f909abe67f6f0b1ce0500f29c576f2953c2e92a977c45b2893277e"
format = "tar.gz"
arch = "x86_64"
macos = "14.0"

[dependencies]
runtime = []
build = []
optional = []

[install]
strategy = "link"
bin = ["mods"]
lib = []
include = []
script = ""

[hints]
post_install = ""
