[package]
name = "mpv"
version = "0.41.0"
description = ""
homepage = "https://github.com/mpv-player/mpv"
license = ""
type = "cli"

[source]
url = "https://github.com/mpv-player/mpv/releases/download/v0.41.0/mpv-v0.41.0-macos-14-arm.zip"
blake3 = "94f4e64434c53d73abd334fa6d37cfc4f1ffc3a9ac7e1845855b486569405f8f"
format = "zip"
strip_components = 1

[binary.x86_64]
url = "https://github.com/mpv-player/mpv/releases/download/v0.41.0/mpv-v0.41.0-macos-14-arm.zip"
blake3 = "94f4e64434c53d73abd334fa6d37cfc4f1ffc3a9ac7e1845855b486569405f8f"
format = "zip"
arch = "x86_64"
macos = "14.0"

[binary.arm64]
url = "https://github.com/mpv-player/mpv/releases/download/v0.41.0/mpv-v0.41.0-macos-14-arm.zip"
blake3 = "94f4e64434c53d73abd334fa6d37cfc4f1ffc3a9ac7e1845855b486569405f8f"
format = "zip"
arch = "arm64"
macos = "14.0"

[dependencies]
runtime = []
build = []
optional = []

[install]
strategy = "link"
bin = ["mpv"]
lib = []
include = []
script = ""

[hints]
post_install = ""
