[package]
name = "neovim"
version = "0.11.5"
description = ""
homepage = "https://github.com/neovim/neovim"
license = ""
type = "cli"

[source]
url = "https://github.com/neovim/neovim/releases/download/v0.11.5/nvim-macos-arm64.tar.gz"
blake3 = "21c039e4cf3ba8163204116799e42f0b7dce9087fa14bfe919cae4e84d1542c8"
format = "tar.gz"
strip_components = 1

[binary.arm64]
url = "https://github.com/neovim/neovim/releases/download/v0.11.5/nvim-macos-arm64.tar.gz"
blake3 = "21c039e4cf3ba8163204116799e42f0b7dce9087fa14bfe919cae4e84d1542c8"
format = "tar.gz"
arch = "arm64"
macos = "14.0"

[binary.x86_64]
url = "https://github.com/neovim/neovim/releases/download/v0.11.5/nvim-macos-x86_64.tar.gz"
blake3 = "3addc67545f8dcd7bf572a636376fb93259912863f4bb50765dce97981056313"
format = "tar.gz"
arch = "x86_64"
macos = "14.0"

[dependencies]
runtime = []
build = []
optional = []

[install]
strategy = "link"
bin = ["neovim"]
lib = []
include = []
script = ""

[hints]
post_install = ""
