[package]
name = "ninja"
version = "1.13.2"
description = "Small build system with a focus on speed"
type = "cli"

[source]
url = "https://github.com/ninja-build/ninja/releases/download/v1.13.2/ninja-mac.zip"
blake3 = "8afdef849b534a3110519a8726a8887f6ec62424c6b820ce787952c2e16f1bd7"
format = "zip"

[binary.arm64]
url = "https://github.com/ninja-build/ninja/releases/download/v1.13.2/ninja-mac.zip"
blake3 = "8afdef849b534a3110519a8726a8887f6ec62424c6b820ce787952c2e16f1bd7"
format = "zip"

[binary.x86_64]
url = "https://github.com/ninja-build/ninja/releases/download/v1.12.1/ninja-mac.zip"
blake3 = "fe37342e051bd8e6e083446c620020e2cea7d935acd1a399e6f4801d31f36e1f"
format = "zip"

[install]
strategy = "link"
bin = ["ninja"]
