[package]
name = "ninja"
version = "1.12.1"
description = "Small build system with a focus on speed"
type = "cli"

[source]
url = "https://github.com/ninja-build/ninja/releases/download/v1.12.1/ninja-mac.zip"
blake3 = "fe37342e051bd8e6e083446c620020e2cea7d935acd1a399e6f4801d31f36e1f"

[binary.arm64]
url = "https://github.com/ninja-build/ninja/releases/download/v1.12.1/ninja-mac.zip"
blake3 = "fe37342e051bd8e6e083446c620020e2cea7d935acd1a399e6f4801d31f36e1f"

[binary.x86_64]
url = "https://github.com/ninja-build/ninja/releases/download/v1.12.1/ninja-mac.zip"
blake3 = "fe37342e051bd8e6e083446c620020e2cea7d935acd1a399e6f4801d31f36e1f"

[install]
bin = ["ninja"]
