[package]
name = "obsidian"
version = "1.10.6"
description = "Private and flexible note-taking app"
type = "app"

[source]
url = "https://github.com/obsidianmd/obsidian-releases/releases/download/v1.10.6/Obsidian-1.10.6.dmg"
blake3 = "33b678dc73294166bfb2149dd84d5b6a51cbeae1f754717eea52b9a4914d61e5"

[binary.arm64]
url = "https://github.com/obsidianmd/obsidian-releases/releases/download/v1.10.6/Obsidian-1.10.6.dmg"
blake3 = "33b678dc73294166bfb2149dd84d5b6a51cbeae1f754717eea52b9a4914d61e5"

[install]
app = "Obsidian.app"
