[package]
name = "osv-scanner"
version = "2.3.1"
description = ""
homepage = "https://github.com/google/osv-scanner"
license = ""
type = "cli"

[source]
url = "https://github.com/google/osv-scanner/releases/download/v2.3.1/osv-scanner_darwin_arm64"
blake3 = "66f312a943041c94ef8b2c0001c0bf45cbc0ecb041d11f6d7bb4ae87ae82d4c4"
format = "binary"
strip_components = 0

[binary.arm64]
url = "https://github.com/google/osv-scanner/releases/download/v2.3.1/osv-scanner_darwin_arm64"
blake3 = "66f312a943041c94ef8b2c0001c0bf45cbc0ecb041d11f6d7bb4ae87ae82d4c4"
format = "binary"
arch = "arm64"
macos = "14.0"

[binary.x86_64]
url = "https://github.com/google/osv-scanner/releases/download/v2.3.1/osv-scanner_darwin_amd64"
blake3 = "5012bf473c8b291091b50d205a182ad6f0702c8357a06eec07ea124bb66500d3"
format = "binary"
arch = "x86_64"
macos = "14.0"

[dependencies]
runtime = []
build = []
optional = []

[install]
strategy = "link"
bin = ["osv-scanner"]
lib = []
include = []
script = ""

[hints]
post_install = ""
