[package]
name = "pastel"
version = "0.11.0"
description = ""
homepage = "https://github.com/sharkdp/pastel"
license = ""
type = "cli"

[source]
url = "https://github.com/sharkdp/pastel/releases/download/v0.11.0/pastel-v0.11.0-aarch64-apple-darwin.tar.gz"
blake3 = "42f7def0a133e4475e6c68db88214a79b22a51ff77693325ea72268f810148d7"
format = "tar.gz"
strip_components = 1

[binary.x86_64]
url = "https://github.com/sharkdp/pastel/releases/download/v0.11.0/pastel-v0.11.0-x86_64-apple-darwin.tar.gz"
blake3 = "af11cbf346def97be9db83e2dde0e429fc09be553e3db742b33925add63ef6f5"
format = "tar.gz"
arch = "x86_64"
macos = "14.0"

[binary.arm64]
url = "https://github.com/sharkdp/pastel/releases/download/v0.11.0/pastel-v0.11.0-aarch64-apple-darwin.tar.gz"
blake3 = "42f7def0a133e4475e6c68db88214a79b22a51ff77693325ea72268f810148d7"
format = "tar.gz"
arch = "arm64"
macos = "14.0"

[dependencies]
runtime = []
build = []
optional = []

[install]
strategy = "link"
bin = ["pastel"]
lib = []
include = []
script = ""

[hints]
post_install = ""
