[package]
name = "procs"
version = "0.14.10"
description = "A modern replacement for 'ps' written in Rust"
homepage = "https://github.com/dalance/procs"
license = ""
type = "cli"

[source]
url = "https://github.com/dalance/procs/releases/download/v0.14.10/procs-v0.14.10-aarch64-mac.zip"
blake3 = "4215cb2f2620f7c0658b644e9afbd844c32cd14593c38938167ba65f8fb19acb"
format = "zip"
strip_components = 1

[binary.x86_64]
url = "https://github.com/dalance/procs/releases/download/v0.14.10/procs-v0.14.10-aarch64-mac.zip"
blake3 = "4215cb2f2620f7c0658b644e9afbd844c32cd14593c38938167ba65f8fb19acb"
format = "zip"
arch = "x86_64"
macos = "14.0"

[binary.arm64]
url = "https://github.com/dalance/procs/releases/download/v0.14.10/procs-v0.14.10-aarch64-mac.zip"
blake3 = "4215cb2f2620f7c0658b644e9afbd844c32cd14593c38938167ba65f8fb19acb"
format = "zip"
arch = "arm64"
macos = "14.0"

[dependencies]
runtime = []
build = []
optional = []

[install]
strategy = "link"
bin = ["procs"]
lib = []
include = []
script = ""

[hints]
post_install = ""
