[package]
name = "pulumi"
version = "3.214.0"
description = ""
homepage = "https://github.com/pulumi/pulumi"
license = ""
type = "cli"

[source]
url = "https://github.com/pulumi/pulumi/releases/download/v3.214.0/pulumi-v3.214.0-darwin-arm64.tar.gz"
blake3 = "de9fc6986ba33ef343c49a9e2da5c7d1196be3a3b581acc4cb2a880261ca07ed"
format = "tar.gz"
strip_components = 1

[binary.arm64]
url = "https://github.com/pulumi/pulumi/releases/download/v3.214.0/pulumi-v3.214.0-darwin-arm64.tar.gz"
blake3 = "de9fc6986ba33ef343c49a9e2da5c7d1196be3a3b581acc4cb2a880261ca07ed"
format = "tar.gz"
arch = "arm64"
macos = "14.0"

[binary.x86_64]
url = "https://github.com/pulumi/pulumi/releases/download/v3.214.0/pulumi-v3.214.0-darwin-x64.tar.gz"
blake3 = "098c065ff8d04251bdd0d177d84f1c31379a6065fa106bdc35699798dfd9566d"
format = "tar.gz"
arch = "x86_64"
macos = "14.0"

[dependencies]
runtime = []
build = []
optional = []

[install]
strategy = "link"
bin = ["pulumi"]
lib = []
include = []
script = ""

[hints]
post_install = ""
