[package]
name = "rg"
version = "15.1.0"
description = "A line-oriented search tool that recursively searches the current directory for a regex pattern"
homepage = "https://github.com/BurntSushi/ripgrep"
license = ""
type = "cli"

[source]
url = "https://github.com/BurntSushi/ripgrep/releases/download/15.1.0/ripgrep-15.1.0-aarch64-apple-darwin.tar.gz"
blake3 = "e11088d3949d9d8e7151bc798f1b75f1e6e764c142f32da04dcd756d5caac9a6"
format = "tar.gz"
strip_components = 1

[binary.arm64]
url = "https://github.com/BurntSushi/ripgrep/releases/download/15.1.0/ripgrep-15.1.0-aarch64-apple-darwin.tar.gz"
blake3 = "e11088d3949d9d8e7151bc798f1b75f1e6e764c142f32da04dcd756d5caac9a6"
format = "tar.gz"
arch = "arm64"
macos = "14.0"

[binary.x86_64]
url = "https://github.com/BurntSushi/ripgrep/releases/download/15.1.0/ripgrep-15.1.0-x86_64-apple-darwin.tar.gz"
blake3 = "19af461934320ea02ba885707f1bb9da13f31d0c5b02b7109a73d3e20f2edb7b"
format = "tar.gz"
arch = "x86_64"
macos = "14.0"

[dependencies]
runtime = []
build = []
optional = []

[install]
strategy = "link"
bin = ["rg"]
lib = []
include = []
script = ""

[hints]
post_install = ""
