[package]
name = "ripgrep"
version = "15.1.0"
description = "Line-oriented search tool that recursively searches directories for a regex pattern"
type = "cli"

[source]
url = "https://github.com/BurntSushi/ripgrep/releases/download/15.1.0/ripgrep-15.1.0-aarch64-apple-darwin.tar.gz"
blake3 = "e11088d3949d9d8e7151bc798f1b75f1e6e764c142f32da04dcd756d5caac9a6"
format = "tar.gz"

[binary.arm64]
url = "https://github.com/BurntSushi/ripgrep/releases/download/15.1.0/ripgrep-15.1.0-aarch64-apple-darwin.tar.gz"
blake3 = "e11088d3949d9d8e7151bc798f1b75f1e6e764c142f32da04dcd756d5caac9a6"
format = "tar.gz"

[install]
strategy = "link"
bin = ["rg"]
