[package]
name = "sad"
version = "0.4.32"
description = ""
homepage = "https://github.com/ms-jpq/sad"
license = ""
type = "cli"

[source]
url = "https://github.com/ms-jpq/sad/releases/download/v0.4.32/aarch64-apple-darwin.zip"
blake3 = "0be59bdde9757d5bbcc2f92134fa3f962097075a0d61993f2232e570a1cccdd6"
format = "zip"
strip_components = 1

[binary.arm64]
url = "https://github.com/ms-jpq/sad/releases/download/v0.4.32/aarch64-apple-darwin.zip"
blake3 = "0be59bdde9757d5bbcc2f92134fa3f962097075a0d61993f2232e570a1cccdd6"
format = "zip"
arch = "arm64"
macos = "14.0"

[binary.x86_64]
url = "https://github.com/ms-jpq/sad/releases/download/v0.4.32/x86_64-apple-darwin.zip"
blake3 = "f288808a9d4cb8105f5ded01b9337d98a3f4c4d33c80404d194ab1e946120215"
format = "zip"
arch = "x86_64"
macos = "14.0"

[dependencies]
runtime = []
build = []
optional = []

[install]
strategy = "link"
bin = ["sad"]
lib = []
include = []
script = ""

[hints]
post_install = ""
