[package]
name = "sccache"
version = "0.12.0"
description = "Shared Compilation Cache"
homepage = "https://github.com/mozilla/sccache"
license = ""
type = "cli"

[source]
url = "https://github.com/mozilla/sccache/releases/download/v0.12.0/sccache-v0.12.0-aarch64-apple-darwin.tar.gz"
blake3 = "2d7b3b4285365944360277bbeee38d50ccd03d9af7b7af2f59f0fa3606adca12"
format = "tar.gz"
strip_components = 1

[binary.x86_64]
url = "https://github.com/mozilla/sccache/releases/download/v0.12.0/sccache-v0.12.0-x86_64-apple-darwin.tar.gz"
blake3 = "cbb7477b0557e4dafe80a2f110c456fe908c8795873b09b72db0046d9a8bc3f2"
format = "tar.gz"
arch = "x86_64"
macos = "14.0"

[binary.arm64]
url = "https://github.com/mozilla/sccache/releases/download/v0.12.0/sccache-v0.12.0-aarch64-apple-darwin.tar.gz"
blake3 = "2d7b3b4285365944360277bbeee38d50ccd03d9af7b7af2f59f0fa3606adca12"
format = "tar.gz"
arch = "arm64"
macos = "14.0"

[dependencies]
runtime = []
build = []
optional = []

[install]
strategy = "link"
bin = ["sccache"]
lib = []
include = []
script = ""

[hints]
post_install = ""
