[package]
name = "sd"
version = "1.0.0"
description = ""
homepage = "https://github.com/chmln/sd"
license = ""
type = "cli"

[source]
url = "https://github.com/chmln/sd/releases/download/v1.0.0/sd-v1.0.0-aarch64-apple-darwin.tar.gz"
blake3 = "6b94f3ccef4e6904a250ffc19f163bfe0e45f2635cfe02155aa52cac5397ef41"
format = "tar.gz"
strip_components = 1

[binary.x86_64]
url = "https://github.com/chmln/sd/releases/download/v1.0.0/sd-v1.0.0-x86_64-apple-darwin.tar.gz"
blake3 = "b19b7a5ed64844e833bf08e2eb541667f14d526884b9071e2d60747041f541e9"
format = "tar.gz"
arch = "x86_64"
macos = "14.0"

[binary.arm64]
url = "https://github.com/chmln/sd/releases/download/v1.0.0/sd-v1.0.0-aarch64-apple-darwin.tar.gz"
blake3 = "6b94f3ccef4e6904a250ffc19f163bfe0e45f2635cfe02155aa52cac5397ef41"
format = "tar.gz"
arch = "arm64"
macos = "14.0"

[dependencies]
runtime = []
build = []
optional = []

[install]
strategy = "link"
bin = ["sd"]
lib = []
include = []
script = ""

[hints]
post_install = ""
