[package]
name = "skaffold"
version = "2.17.0"
description = ""
homepage = "https://github.com/GoogleContainerTools/skaffold"
license = ""
type = "cli"

[source]
url = "https://github.com/GoogleContainerTools/skaffold/releases/download/v2.17.0/skaffold-darwin-arm64"
blake3 = "a93c9c47f06188e41efa7b97d66f6807deb3bfaebd9283099689dc656c3e92a7"
format = "binary"
strip_components = 0

[binary.x86_64]
url = "https://github.com/GoogleContainerTools/skaffold/releases/download/v2.17.0/skaffold-darwin-amd64"
blake3 = "5767a27be066f57ecd85696a7d15cb40c0363c4fd1b0a42b7a9eab0629a61689"
format = "binary"
arch = "x86_64"
macos = "14.0"

[binary.arm64]
url = "https://github.com/GoogleContainerTools/skaffold/releases/download/v2.17.0/skaffold-darwin-arm64"
blake3 = "a93c9c47f06188e41efa7b97d66f6807deb3bfaebd9283099689dc656c3e92a7"
format = "binary"
arch = "arm64"
macos = "14.0"

[dependencies]
runtime = []
build = []
optional = []

[install]
strategy = "link"
bin = ["skaffold"]
lib = []
include = []
script = ""

[hints]
post_install = ""
