[package]
name = "slides"
version = "0.9.0"
description = "Terminal based presentation tool"
homepage = "https://github.com/maaslalani/slides"
license = ""
type = "cli"

[source]
url = "https://github.com/maaslalani/slides/releases/download/v0.9.0/slides_0.9.0_darwin_arm64.tar.gz"
blake3 = "27fe5188cd812e525bad32785e2b555eeb9a345917aafae3be13993592f37d34"
format = "tar.gz"
strip_components = 1

[binary.x86_64]
url = "https://github.com/maaslalani/slides/releases/download/v0.9.0/slides_0.9.0_darwin_amd64.tar.gz"
blake3 = "8e75e9d62a2526da19e3949089ea9e40bcd9b2423ce44797963596927ce3b927"
format = "tar.gz"
arch = "x86_64"
macos = "14.0"

[binary.arm64]
url = "https://github.com/maaslalani/slides/releases/download/v0.9.0/slides_0.9.0_darwin_arm64.tar.gz"
blake3 = "27fe5188cd812e525bad32785e2b555eeb9a345917aafae3be13993592f37d34"
format = "tar.gz"
arch = "arm64"
macos = "14.0"

[dependencies]
runtime = []
build = []
optional = []

[install]
strategy = "link"
bin = ["slides"]
lib = []
include = []
script = ""

[hints]
post_install = ""
