[package]
name = "slsa-verifier"
version = "2.7.1"
description = ""
homepage = "https://github.com/slsa-framework/slsa-verifier"
license = ""
type = "cli"

[source]
url = "https://github.com/slsa-framework/slsa-verifier/releases/download/v2.7.1/slsa-verifier-darwin-arm64"
blake3 = "af93f77462964b7eeb93b9f45ccedeefc641305f6618d9ffc2480d89b0cceed6"
format = "binary"
strip_components = 0

[binary.arm64]
url = "https://github.com/slsa-framework/slsa-verifier/releases/download/v2.7.1/slsa-verifier-darwin-arm64"
blake3 = "af93f77462964b7eeb93b9f45ccedeefc641305f6618d9ffc2480d89b0cceed6"
format = "binary"
arch = "arm64"
macos = "14.0"

[binary.x86_64]
url = "https://github.com/slsa-framework/slsa-verifier/releases/download/v2.7.1/slsa-verifier-darwin-amd64"
blake3 = "75eee71fd725d12dc3097c9792946cb228757eff4d8b5af901b87aa22ddbe2d8"
format = "binary"
arch = "x86_64"
macos = "14.0"

[dependencies]
runtime = []
build = []
optional = []

[install]
strategy = "link"
bin = ["slsa-verifier"]
lib = []
include = []
script = ""

[hints]
post_install = ""
