[package]
name = "soft-serve"
version = "0.11.1"
description = ""
homepage = "https://github.com/charmbracelet/soft-serve"
license = ""
type = "cli"

[source]
url = "https://github.com/charmbracelet/soft-serve/releases/download/v0.11.1/soft-serve_0.11.1_Darwin_arm64.tar.gz"
blake3 = "c46331fe19f257050cf83f0bec9ef81e18b4218a2b0ddea118a9b2f4d335e62c"
format = "tar.gz"
strip_components = 1

[binary.arm64]
url = "https://github.com/charmbracelet/soft-serve/releases/download/v0.11.1/soft-serve_0.11.1_Darwin_arm64.tar.gz"
blake3 = "c46331fe19f257050cf83f0bec9ef81e18b4218a2b0ddea118a9b2f4d335e62c"
format = "tar.gz"
arch = "arm64"
macos = "14.0"

[binary.x86_64]
url = "https://github.com/charmbracelet/soft-serve/releases/download/v0.11.1/soft-serve_0.11.1_Darwin_x86_64.tar.gz"
blake3 = "6bc3def2636f0e6a016210bf131a43afd9184c29e137d77d564a4160a7aeb1df"
format = "tar.gz"
arch = "x86_64"
macos = "14.0"

[dependencies]
runtime = []
build = []
optional = []

[install]
strategy = "link"
bin = ["soft-serve"]
lib = []
include = []
script = ""

[hints]
post_install = ""
