[package]
name = "starship"
version = "1.24.2"
description = "The minimal, blazing-fast, and infinitely customizable prompt for any shell!"
homepage = "https://github.com/starship/starship"
license = ""
type = "cli"

[source]
url = "https://github.com/starship/starship/releases/download/v1.24.2/starship-aarch64-apple-darwin.tar.gz"
blake3 = "67c03f30cefeb63feb2456003324c68925787f363e550a1fef58ac4bf97d54d4"
format = "tar.gz"
strip_components = 1

[binary.arm64]
url = "https://github.com/starship/starship/releases/download/v1.24.2/starship-aarch64-apple-darwin.tar.gz"
blake3 = "67c03f30cefeb63feb2456003324c68925787f363e550a1fef58ac4bf97d54d4"
format = "tar.gz"
arch = "arm64"
macos = "14.0"

[binary.x86_64]
url = "https://github.com/starship/starship/releases/download/v1.24.2/starship-x86_64-apple-darwin.tar.gz"
blake3 = "8bdc5133ad1684ba8caa4a346b74c8a3df03900c33185d374f27bb04fe7cfce7"
format = "tar.gz"
arch = "x86_64"
macos = "14.0"

[dependencies]
runtime = []
build = []
optional = []

[install]
strategy = "link"
bin = ["starship"]
lib = []
include = []
script = ""

[hints]
post_install = ""
