[package]
name = "starship"
version = "1.24.2"
description = ""
homepage = ""
license = ""
type = "cli"

[source]
url = "https://github.com/starship/starship/releases/download/v1.24.2/starship-aarch64-apple-darwin.tar.gz"
blake3 = "67c03f30cefeb63feb2456003324c68925787f363e550a1fef58ac4bf97d54d4"
format = "tar.gz"
strip_components = 1

[binary.arm64]
url = "https://github.com/starship/starship/releases/download/v1.24.2/starship-aarch64-apple-darwin.tar.gz"
blake3 = "67c03f30cefeb63feb2456003324c68925787f363e550a1fef58ac4bf97d54d4"
format = "tar.gz"

[dependencies]
runtime = []
build = []
optional = []

[install]
strategy = "link"
bin = ["starship"]

[hints]
post_install = ""
