[package]
name = "syncthing"
version = "2.0.12"
description = ""
homepage = "https://github.com/syncthing/syncthing"
license = ""
type = "cli"

[source]
url = "https://github.com/syncthing/syncthing/releases/download/v2.0.12/syncthing-macos-arm64-v2.0.12.zip"
blake3 = "5e40392e9a29af291cf3492a930b46833d53a5699922aa49441627d9f2fe2bee"
format = "zip"
strip_components = 1

[binary.arm64]
url = "https://github.com/syncthing/syncthing/releases/download/v2.0.12/syncthing-macos-arm64-v2.0.12.zip"
blake3 = "5e40392e9a29af291cf3492a930b46833d53a5699922aa49441627d9f2fe2bee"
format = "zip"
arch = "arm64"
macos = "14.0"

[binary.x86_64]
url = "https://github.com/syncthing/syncthing/releases/download/v2.0.12/syncthing-macos-amd64-v2.0.12.zip"
blake3 = "30f300de9194986f737dcbaf04d095de5a39e520ff7bde4838a8afcaa04c55dc"
format = "zip"
arch = "x86_64"
macos = "14.0"

[dependencies]
runtime = []
build = []
optional = []

[install]
strategy = "link"
bin = ["syncthing"]
lib = []
include = []
script = ""

[hints]
post_install = ""
