[package]
name = "tealdeer"
version = "1.8.1"
description = "A very fast implementation of tldr in Rust"
homepage = "https://github.com/dbrgn/tealdeer"
license = ""
type = "cli"

[source]
url = "https://github.com/tealdeer-rs/tealdeer/releases/download/v1.8.1/tealdeer-macos-aarch64"
blake3 = "ce413f2ea79449c7377b382b9f391d597bb24e2b62ea4b01994f7a5519a41ec5"
format = "binary"
strip_components = 0

[binary.x86_64]
url = "https://github.com/tealdeer-rs/tealdeer/releases/download/v1.8.1/tealdeer-macos-x86_64"
blake3 = "5060d2d4e5a695a7b2d0d3de279f6264c392b39d4dcd2b3aac3194ef29b9323b"
format = "binary"
arch = "x86_64"
macos = "14.0"

[binary.arm64]
url = "https://github.com/tealdeer-rs/tealdeer/releases/download/v1.8.1/tealdeer-macos-aarch64"
blake3 = "ce413f2ea79449c7377b382b9f391d597bb24e2b62ea4b01994f7a5519a41ec5"
format = "binary"
arch = "arm64"
macos = "14.0"

[dependencies]
runtime = []
build = []
optional = []

[install]
strategy = "link"
bin = ["tealdeer"]
lib = []
include = []
script = ""

[hints]
post_install = ""
