[package]
name = "termshot"
version = "0.6.0"
description = "Capture polished terminal output as images"
homepage = "https://github.com/homeport/termshot"
license = ""
type = "cli"

[source]
url = "https://github.com/homeport/termshot/releases/download/v0.6.0/termshot_0.6.0_darwin_arm64.tar.gz"
blake3 = "f0da87d09dfc818551a6ba649c0fc96a0940331baff9d95ec46b5bef556dbb18"
format = "tar.gz"
strip_components = 1

[binary.arm64]
url = "https://github.com/homeport/termshot/releases/download/v0.6.0/termshot_0.6.0_darwin_arm64.tar.gz"
blake3 = "f0da87d09dfc818551a6ba649c0fc96a0940331baff9d95ec46b5bef556dbb18"
format = "tar.gz"
arch = "arm64"
macos = "14.0"

[binary.x86_64]
url = "https://github.com/homeport/termshot/releases/download/v0.6.0/termshot_0.6.0_darwin_amd64.tar.gz"
blake3 = "b39e9cb1a9c0924ad6df976807252a1292f9f7925af70ce40f35dd8dab4d44ee"
format = "tar.gz"
arch = "x86_64"
macos = "14.0"

[dependencies]
runtime = []
build = []
optional = []

[install]
strategy = "link"
bin = ["termshot"]
lib = []
include = []
script = ""

[hints]
post_install = ""
