[package]
name = "tofu"
version = "1.11.2"
description = "Open-source Infrastructure as Code tool managed by the Linux Foundation"
homepage = "https://github.com/opentofu/opentofu"
license = ""
type = "cli"

[source]
url = "https://github.com/opentofu/opentofu/releases/download/v1.11.2/tofu_1.11.2_darwin_arm64.tar.gz"
blake3 = "0fa5f67e5dd342b0e0159f9526925dadec0ccd88f97aae56247cfcdfd794c6ae"
format = "tar.gz"
strip_components = 1

[binary.x86_64]
url = "https://github.com/opentofu/opentofu/releases/download/v1.11.2/tofu_1.11.2_darwin_amd64.tar.gz"
blake3 = "0340aba70f8d88ab3f0a7c4b3aa6714f35ee952b874c2a74076baf5b5cf86ab1"
format = "tar.gz"
arch = "x86_64"
macos = "14.0"

[binary.arm64]
url = "https://github.com/opentofu/opentofu/releases/download/v1.11.2/tofu_1.11.2_darwin_arm64.tar.gz"
blake3 = "0fa5f67e5dd342b0e0159f9526925dadec0ccd88f97aae56247cfcdfd794c6ae"
format = "tar.gz"
arch = "arm64"
macos = "14.0"

[dependencies]
runtime = []
build = []
optional = []

[install]
strategy = "link"
bin = ["tofu"]
lib = []
include = []
script = ""

[hints]
post_install = ""
