[package]
name = "tokei"
version = "0.0.0"
description = ""
homepage = ""
license = ""
type = "cli"

[source]
url = "https://github.com/XAMPPRocky/tokei"
blake3 = ""
strip_components = 1

[binary]

[dependencies]
runtime = []
build = []
optional = []

[install]
bin = ["tokei"]

[hints]
post_install = ""
