[package]
name = "transmission"
version = "4.0.6"
description = ""
homepage = "https://github.com/transmission/transmission"
license = ""
type = "cli"

[source]
url = "https://github.com/transmission/transmission/releases/download/4.0.6/Transmission-4.0.6.dmg"
blake3 = "ee2149d3700cccecb75b9dcbe8893321c7a4fb4b9f2d01e777bd57518fa8cc22"
format = "dmg"
strip_components = 1

[binary.arm64]
url = "https://github.com/transmission/transmission/releases/download/4.0.6/Transmission-4.0.6.dmg"
blake3 = "ee2149d3700cccecb75b9dcbe8893321c7a4fb4b9f2d01e777bd57518fa8cc22"
format = "dmg"
arch = "arm64"
macos = "14.0"

[binary.x86_64]
url = "https://github.com/transmission/transmission/releases/download/4.0.6/Transmission-4.0.6.dmg"
blake3 = "ee2149d3700cccecb75b9dcbe8893321c7a4fb4b9f2d01e777bd57518fa8cc22"
format = "dmg"
arch = "x86_64"
macos = "14.0"

[dependencies]
runtime = []
build = []
optional = []

[install]
strategy = "link"
bin = ["transmission"]
lib = []
include = []
script = ""

[hints]
post_install = ""
