[package]
name = "trivy"
version = "0.68.2"
description = "Find vulnerabilities, misconfigurations, secrets, SBOM in containers, Kubernetes, code repositories, clouds and more"
homepage = "https://github.com/aquasecurity/trivy"
license = ""
type = "cli"

[source]
url = "https://github.com/aquasecurity/trivy/releases/download/v0.68.2/trivy_0.68.2_macOS-ARM64.tar.gz"
blake3 = "cc0540bb803433563dec964c9163196a9384fbf5a2cee02a3a5ce03c2956df9b"
format = "tar.gz"
strip_components = 1

[binary.x86_64]
url = "https://github.com/aquasecurity/trivy/releases/download/v0.68.2/trivy_0.68.2_macOS-64bit.tar.gz"
blake3 = "93bc8cd02c0f267e0181aa0b82c6cf9d577336b2e78c9c0dacca48245f75fa92"
format = "tar.gz"
arch = "x86_64"
macos = "14.0"

[binary.arm64]
url = "https://github.com/aquasecurity/trivy/releases/download/v0.68.2/trivy_0.68.2_macOS-ARM64.tar.gz"
blake3 = "cc0540bb803433563dec964c9163196a9384fbf5a2cee02a3a5ce03c2956df9b"
format = "tar.gz"
arch = "arm64"
macos = "14.0"

[dependencies]
runtime = []
build = []
optional = []

[install]
strategy = "link"
bin = ["trivy"]
lib = []
include = []
script = ""

[hints]
post_install = ""
