[package]
name = "trufflehog"
version = "3.92.4"
description = "Find, verify, and analyze leaked credentials"
homepage = "https://github.com/trufflesecurity/trufflehog"
license = ""
type = "cli"

[source]
url = "https://github.com/trufflesecurity/trufflehog/releases/download/v3.92.4/trufflehog_3.92.4_darwin_arm64.tar.gz"
blake3 = "44da45730497bcffdaa63b8ee766cbdfe9aa260bdfb6f128e36028d9fcf60882"
format = "tar.gz"
strip_components = 1

[binary.arm64]
url = "https://github.com/trufflesecurity/trufflehog/releases/download/v3.92.4/trufflehog_3.92.4_darwin_arm64.tar.gz"
blake3 = "44da45730497bcffdaa63b8ee766cbdfe9aa260bdfb6f128e36028d9fcf60882"
format = "tar.gz"
arch = "arm64"
macos = "14.0"

[binary.x86_64]
url = "https://github.com/trufflesecurity/trufflehog/releases/download/v3.92.4/trufflehog_3.92.4_darwin_amd64.tar.gz"
blake3 = "a5e07c060d8861bc8bb42236daab8df58d358cb85451e949461e292db4aa61a3"
format = "tar.gz"
arch = "x86_64"
macos = "14.0"

[dependencies]
runtime = []
build = []
optional = []

[install]
strategy = "link"
bin = ["trufflehog"]
lib = []
include = []
script = ""

[hints]
post_install = ""
