[package]
name = "typos"
version = "1.41.0"
description = "Source code spell checker"
homepage = "https://github.com/crate-ci/typos"
license = ""
type = "cli"

[source]
url = "https://github.com/crate-ci/typos/releases/download/v1.41.0/typos-v1.41.0-aarch64-apple-darwin.tar.gz"
blake3 = "dd5d2793c9342af303cce5185bd2736d39e98298872df630951001575cb9192d"
format = "tar.gz"
strip_components = 1

[binary.x86_64]
url = "https://github.com/crate-ci/typos/releases/download/v1.41.0/typos-v1.41.0-x86_64-apple-darwin.tar.gz"
blake3 = "14f097ddf58dc7008d555ab236357c5666f06dd5d95660dc947999b8565fac62"
format = "tar.gz"
arch = "x86_64"
macos = "14.0"

[binary.arm64]
url = "https://github.com/crate-ci/typos/releases/download/v1.41.0/typos-v1.41.0-aarch64-apple-darwin.tar.gz"
blake3 = "dd5d2793c9342af303cce5185bd2736d39e98298872df630951001575cb9192d"
format = "tar.gz"
arch = "arm64"
macos = "14.0"

[dependencies]
runtime = []
build = []
optional = []

[install]
strategy = "link"
bin = ["typos"]
lib = []
include = []
script = ""

[hints]
post_install = ""
