[package]
name = "vhs"
version = "0.10.0"
description = ""
homepage = "https://github.com/charmbracelet/vhs"
license = ""
type = "cli"

[source]
url = "https://github.com/charmbracelet/vhs/releases/download/v0.10.0/vhs_0.10.0_Darwin_arm64.tar.gz"
blake3 = "01e233b4dec617ec9136c206f74e0c00c910f78e75e763dc5a6d73ccb5b1cbdb"
format = "tar.gz"
strip_components = 1

[binary.x86_64]
url = "https://github.com/charmbracelet/vhs/releases/download/v0.10.0/vhs_0.10.0_Darwin_x86_64.tar.gz"
blake3 = "1bebc5bb3082a54aebd47aab539aaa169516b7fc9b6e7f6acc339fd52f302d1e"
format = "tar.gz"
arch = "x86_64"
macos = "14.0"

[binary.arm64]
url = "https://github.com/charmbracelet/vhs/releases/download/v0.10.0/vhs_0.10.0_Darwin_arm64.tar.gz"
blake3 = "01e233b4dec617ec9136c206f74e0c00c910f78e75e763dc5a6d73ccb5b1cbdb"
format = "tar.gz"
arch = "arm64"
macos = "14.0"

[dependencies]
runtime = []
build = []
optional = []

[install]
strategy = "link"
bin = ["vhs"]
lib = []
include = []
script = ""

[hints]
post_install = ""
