[package]
name = "viddy"
version = "1.3.0"
description = ""
homepage = "https://github.com/sachaos/viddy"
license = ""
type = "cli"

[source]
url = "https://github.com/sachaos/viddy/releases/download/v1.3.0/viddy-v1.3.0-macos-arm64.tar.gz"
blake3 = "9e7ef02670760136609270ca87f7143d8103b4a88d0abd6b5c567108ff688164"
format = "tar.gz"
strip_components = 1

[binary.x86_64]
url = "https://github.com/sachaos/viddy/releases/download/v1.3.0/viddy-v1.3.0-macos-x86_64.tar.gz"
blake3 = "45c721a35b12934a4ecd19ca32fecfdfe45717c8db48e045ff7a66dbda904d86"
format = "tar.gz"
arch = "x86_64"
macos = "14.0"

[binary.arm64]
url = "https://github.com/sachaos/viddy/releases/download/v1.3.0/viddy-v1.3.0-macos-arm64.tar.gz"
blake3 = "9e7ef02670760136609270ca87f7143d8103b4a88d0abd6b5c567108ff688164"
format = "tar.gz"
arch = "arm64"
macos = "14.0"

[dependencies]
runtime = []
build = []
optional = []

[install]
strategy = "link"
bin = ["viddy"]
lib = []
include = []
script = ""

[hints]
post_install = ""
