[package]
name = "vlc"
version = "3.0.21"
description = "VLC media player is a free and open source cross-platform multimedia player"
type = "app"

[source]
url = "https://download.videolan.org/pub/videolan/vlc/3.0.21/macosx/vlc-3.0.21-arm64.dmg"
blake3 = "81884ac7c1a8c4594616c5d8d8cc76d55486750163dc0ab1120545c7603a67d8"
format = "dmg"

[binary.arm64]
url = "https://download.videolan.org/pub/videolan/vlc/3.0.21/macosx/vlc-3.0.21-arm64.dmg"
blake3 = "81884ac7c1a8c4594616c5d8d8cc76d55486750163dc0ab1120545c7603a67d8"
format = "dmg"

[install]
strategy = "app"
app = "VLC.app"
