[package]
name = "volta"
version = "2.0.2"
description = "The Hassle-Free JavaScript Tool Manager"
homepage = "https://github.com/volta-cli/volta"
license = ""
type = "cli"

[source]
url = "https://github.com/volta-cli/volta/releases/download/v2.0.2/volta-2.0.2-macos.tar.gz"
blake3 = "f028146372745d36b2377484c103b0bf426ff2b0fd519042f1512fc5b0ab48cd"
format = "tar.gz"
strip_components = 1

[binary.arm64]
url = "https://github.com/volta-cli/volta/releases/download/v2.0.2/volta-2.0.2-macos.tar.gz"
blake3 = "f028146372745d36b2377484c103b0bf426ff2b0fd519042f1512fc5b0ab48cd"
format = "tar.gz"
arch = "arm64"
macos = "14.0"

[binary.x86_64]
url = "https://github.com/volta-cli/volta/releases/download/v2.0.2/volta-2.0.2-macos.tar.gz"
blake3 = "f028146372745d36b2377484c103b0bf426ff2b0fd519042f1512fc5b0ab48cd"
format = "tar.gz"
arch = "x86_64"
macos = "14.0"

[dependencies]
runtime = []
build = []
optional = []

[install]
strategy = "link"
bin = ["volta"]
lib = []
include = []
script = ""

[hints]
post_install = ""
