[package]
name = "watchexec"
version = "2.3.2"
description = ""
homepage = "https://github.com/watchexec/watchexec"
license = ""
type = "cli"

[source]
url = "https://github.com/watchexec/watchexec/releases/download/v2.3.2/watchexec-2.3.2-aarch64-apple-darwin.tar.xz"
blake3 = "31d8c3c5f9b287ef145b22e2cfa58569099a93e0794e824daeef4231969f7e45"
format = "tar"
strip_components = 1

[binary.arm64]
url = "https://github.com/watchexec/watchexec/releases/download/v2.3.2/watchexec-2.3.2-aarch64-apple-darwin.tar.xz"
blake3 = "31d8c3c5f9b287ef145b22e2cfa58569099a93e0794e824daeef4231969f7e45"
format = "tar"
arch = "arm64"
macos = "14.0"

[binary.x86_64]
url = "https://github.com/watchexec/watchexec/releases/download/v2.3.2/watchexec-2.3.2-x86_64-apple-darwin.tar.xz"
blake3 = "f7142342ae3567bb661d01f41c901dc30b1dea0a6c9ca2945ebff3865a89d523"
format = "tar"
arch = "x86_64"
macos = "14.0"

[dependencies]
runtime = []
build = []
optional = []

[install]
strategy = "link"
bin = ["watchexec"]
lib = []
include = []
script = ""

[hints]
post_install = ""
