[package]
name = "wezterm"
version = "20240203-110809-5046fc22"
description = ""
homepage = "https://github.com/wez/wezterm"
license = ""
type = "cli"

[source]
url = "https://github.com/wezterm/wezterm/releases/download/20240203-110809-5046fc22/WezTerm-macos-20240203-110809-5046fc22.zip"
blake3 = "ac1b63926c12cf382f8d82804bb3a873d97acefc5d673a8ed59c5d8d0c6badaf"
format = "zip"
strip_components = 1

[binary.x86_64]
url = "https://github.com/wezterm/wezterm/releases/download/20240203-110809-5046fc22/WezTerm-macos-20240203-110809-5046fc22.zip"
blake3 = "ac1b63926c12cf382f8d82804bb3a873d97acefc5d673a8ed59c5d8d0c6badaf"
format = "zip"
arch = "x86_64"
macos = "14.0"

[binary.arm64]
url = "https://github.com/wezterm/wezterm/releases/download/20240203-110809-5046fc22/WezTerm-macos-20240203-110809-5046fc22.zip"
blake3 = "ac1b63926c12cf382f8d82804bb3a873d97acefc5d673a8ed59c5d8d0c6badaf"
format = "zip"
arch = "arm64"
macos = "14.0"

[dependencies]
runtime = []
build = []
optional = []

[install]
strategy = "link"
bin = ["wezterm"]
lib = []
include = []
script = ""

[hints]
post_install = ""
