[package]
name = "zed"
version = "0.217.3"
description = "A high-performance, multiplayer code editor"
homepage = "https://github.com/zed-industries/zed"
license = ""
type = "cli"

[source]
url = "https://github.com/zed-industries/zed/releases/download/v0.217.3/Zed-aarch64.dmg"
blake3 = "30c69b9adc851a11b8a3857dfae7e0cd50ef2bc4968d5e8f56af064519235810"
format = "dmg"
strip_components = 1

[binary.x86_64]
url = "https://github.com/zed-industries/zed/releases/download/v0.217.3/zed-linux-x86_64.tar.gz"
blake3 = "451632ad04c62f697537687c6d000c9f31df67d61d90c006388b8a9eb6d550b5"
format = "dmg"
arch = "x86_64"
macos = "14.0"

[binary.arm64]
url = "https://github.com/zed-industries/zed/releases/download/v0.217.3/Zed-aarch64.dmg"
blake3 = "30c69b9adc851a11b8a3857dfae7e0cd50ef2bc4968d5e8f56af064519235810"
format = "dmg"
arch = "arm64"
macos = "14.0"

[dependencies]
runtime = []
build = []
optional = []

[install]
strategy = "link"
bin = ["zed"]
lib = []
include = []
script = ""

[hints]
post_install = ""
