[package]
name = "zoxide"
version = "0.9.8"
description = ""
homepage = ""
license = ""
type = "cli"

[source]
url = "https://github.com/ajeetdsouza/zoxide/releases/download/v0.9.8/zoxide-0.9.8-aarch64-apple-darwin.tar.gz"
blake3 = "225180129d7d87f7d55eaaf13b065e8ac95123347734e41c01da13ade4b4664f"
strip_components = 1

[binary]

[dependencies]
runtime = []
build = []
optional = []

[install]
bin = ["zoxide"]

[hints]
post_install = ""
