[package]
name = "zoxide"
version = "0.9.8"
description = "A smarter cd command"
homepage = "https://github.com/ajeetdsouza/zoxide"
license = ""
type = "cli"

[source]
url = "https://github.com/ajeetdsouza/zoxide/releases/download/v0.9.8/zoxide-0.9.8-aarch64-apple-darwin.tar.gz"
blake3 = "225180129d7d87f7d55eaaf13b065e8ac95123347734e41c01da13ade4b4664f"
format = "tar.gz"
strip_components = 1

[binary.x86_64]
url = "https://github.com/ajeetdsouza/zoxide/releases/download/v0.9.8/zoxide-0.9.8-x86_64-apple-darwin.tar.gz"
blake3 = "3dff909817872b7448fabfa35742245fb8b1d7e4bd5ba6f3229cf0610ef7ea7a"
format = "tar.gz"
arch = "x86_64"
macos = "14.0"

[binary.arm64]
url = "https://github.com/ajeetdsouza/zoxide/releases/download/v0.9.8/zoxide-0.9.8-aarch64-apple-darwin.tar.gz"
blake3 = "225180129d7d87f7d55eaaf13b065e8ac95123347734e41c01da13ade4b4664f"
format = "tar.gz"
arch = "arm64"
macos = "14.0"

[dependencies]
runtime = []
build = []
optional = []

[install]
strategy = "link"
bin = ["zoxide"]
lib = []
include = []
script = ""

[hints]
post_install = ""
