[package]
name = "infisical"
description = "Infisical is the open source secret management platform."
homepage = "https://infisical.com"

[discovery]
github = "Infisical/infisical"
tag_pattern = "v{{version}}"

[assets]
arm64-macos = { regex = ".*darwin_arm64.*" }
x86_64-macos = { regex = ".*darwin_amd64.*" }

[install]
bin = ["infisical"]
