[package]
name = "neovim"
description = "Vim-fork focused on extensibility and usability"
homepage = "https://github.com/neovim/neovim"
license = ""

[discovery]
github = "neovim/neovim"
tag_pattern = "v{{version}}"
include_prereleases = false

[assets]
universal = false
skip_checksums = false

[assets.arm64-macos]
suffix = "arm64.tar.gz"

[assets.x86_64-macos]
suffix = "x86_64.tar.gz"

[install]
bin = ["nvim"]
lib = []
include = []
script = ""

[hints]
post_install = ""
