name: Update Ports

on:
  schedule:
    - cron: '0 * * * *' # Run hourly
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
  APL_ARTIFACT_STORE_BUCKET: apl-store

jobs:
  update-ports:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        
      - name: Build and Run Engine
        run: |
          cargo run -p apl-ports
