[package]
name = "ouch"
description = "A command-line tool to help you compress and decompress files/directories."
homepage = "https://github.com/ouch-org/ouch"

[discovery]
github = "ouch-org/ouch"
tag_pattern = "v{{version}}"

[assets]
arm64-macos = { regex = "ouch-.*-aarch64-apple-darwin\\.tar\\.gz" }
x86_64-macos = { regex = "ouch-.*-x86_64-apple-darwin\\.tar\\.gz" }

[install]
bin = ["ouch"]
